import { getOperationActionBinding } from './operationActionMap.js';

/**
 * Presentation-only Operations catalog.
 *
 * displayCommand is shown in the console UI but is never an execution string.
 * Only actions with an allowlisted backend binding are exported to the UI.
 */

export const OPERATION_RISK_LEVELS = Object.freeze([
  'safe',
  'moderate',
  'high',
  'critical',
]);

export const OPERATION_AVAILABILITY = Object.freeze({
  AVAILABLE: 'available',
});

export const OPERATION_ROLES = Object.freeze([
  'observer',
  'operator',
  'administrator',
  'validator',
]);

const VALIDATOR_ONLY_DISABLED_REASON = 'Available only when the selected node type is Validator Node.';

function plainTooltip(value, fallback) {
  const text = String(value || fallback || '').trim();
  return text
    .replace(/^Planned:\s*/i, '')
    .replace(/^Planned tools\b/i, 'Tools');
}

function availableAction(categoryId, action) {
  const allowedRoles = action.allowedRoles || (action.validatorOnly
    ? ['validator', 'administrator']
    : action.riskLevel === 'safe' && !action.requiresConfirmation
      ? ['observer', 'operator', 'administrator']
      : ['operator', 'administrator']);

  return Object.freeze({
    actionId: action.actionId,
    categoryId,
    label: action.label,
    description: action.description,
    tooltip: plainTooltip(action.tooltip, action.description),
    displayCommand: action.displayCommand,
    icon: action.icon,
    status: OPERATION_AVAILABILITY.AVAILABLE,
    availability: OPERATION_AVAILABILITY.AVAILABLE,
    executionMode: 'allowlisted-backend',
    riskLevel: action.riskLevel,
    requiresConfirmation: action.requiresConfirmation,
    requiresWalletConfirmation: action.requiresWalletConfirmation,
    requiresOwnerWallet: action.requiresOwnerWallet,
    validatorOnly: action.validatorOnly,
    allowedRoles: Object.freeze(allowedRoles),
    disabledReason: action.validatorOnly ? VALIDATOR_ONLY_DISABLED_REASON : null,
  });
}

function category({ id, order, label, description, tooltip, icon, accent, actions }) {
  const executableActions = actions.filter((action) => getOperationActionBinding(action.actionId));

  return Object.freeze({
    id,
    order,
    label,
    description,
    tooltip: plainTooltip(tooltip, description),
    icon,
    accent,
    actions: Object.freeze(executableActions.map((action) => availableAction(id, action))),
  });
}

const UNSORTED_OPERATION_CATEGORIES = [
  category({
    id: 'lifecycle',
    order: 1,
    label: 'Lifecycle',
    description: 'Control the node process and lifecycle.',
    tooltip: 'Planned tools for checking and managing this node.',
    icon: 'Power',
    accent: '#22c55e',
    actions: [
      {
        actionId: 'operations.lifecycle.view-status',
        label: 'View Status',
        description: 'Inspect runtime status and current service health.',
        tooltip: 'Planned: See whether this node is running and healthy.',
        displayCommand: 'synergy node status',
        icon: 'Eye',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.start-node',
        label: 'Start Node',
        description: 'Start the selected Synergy node runtime.',
        tooltip: 'Planned: Start this Synergy node.',
        displayCommand: 'synergy node start',
        icon: 'Play',
        riskLevel: 'moderate',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.stop-node',
        label: 'Stop Node',
        description: 'Stop the selected node runtime and its active duties.',
        tooltip: 'Planned: Stop this node and its active duties.',
        displayCommand: 'synergy node stop',
        icon: 'Square',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.restart-node',
        label: 'Restart Node',
        description: 'Restart the selected node runtime.',
        tooltip: 'Planned: Restart this node.',
        displayCommand: 'synergy node restart',
        icon: 'RotateCw',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.safe-shutdown',
        label: 'Safe Shutdown',
        description: 'Check current node activity, then request a graceful runtime stop.',
        tooltip: 'Planned: Check node activity, then ask the service to stop cleanly.',
        displayCommand: 'synergy node shutdown --safe',
        icon: 'ShieldCheck',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.emergency-stop',
        label: 'Emergency Stop',
        description: 'Immediately stop the runtime. This can interrupt active duties.',
        tooltip: 'Planned: Stop this node immediately, even if work is active.',
        displayCommand: 'synergy node stop --emergency',
        icon: 'OctagonAlert',
        riskLevel: 'critical',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.reload-config',
        label: 'Reload Config',
        description: 'Reload supported runtime configuration without replacing identity material.',
        tooltip: 'Planned: Reload supported settings without replacing this node identity.',
        displayCommand: 'synergy node config reload',
        icon: 'RefreshCw',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.enable-auto-start',
        label: 'Enable Auto-Start',
        description: 'Configure the runtime to start automatically after host restart.',
        tooltip: 'Planned: Start this node automatically after the host restarts.',
        displayCommand: 'synergy node autostart enable',
        icon: 'Power',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.lifecycle.disable-auto-start',
        label: 'Disable Auto-Start',
        description: 'Prevent the runtime from starting automatically after host restart.',
        tooltip: 'Planned: Prevent this node from starting after the host restarts.',
        displayCommand: 'synergy node autostart disable',
        icon: 'PowerOff',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'network-vpn',
    order: 2,
    label: 'Network & VPN',
    description: 'Inspect secure-network routes, peers, and connectivity.',
    tooltip: 'Planned tools for checking this node\'s private network connections.',
    icon: 'Network',
    accent: '#22d3ee',
    actions: [
      {
        actionId: 'operations.network-vpn.vpn-status',
        label: 'VPN Status',
        description: 'Show VPN connection state, route health, and latency.',
        tooltip: 'Planned: See whether the private network connection is healthy.',
        displayCommand: 'synergy node vpn status',
        icon: 'Shield',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.innernet-status',
        label: 'Innernet Status',
        description: 'Check private-network connectivity and assigned transport routes.',
        tooltip: 'Planned: Check the private network connection and assigned routes.',
        displayCommand: 'synergy node innernet status',
        icon: 'Network',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.restart-vpn',
        label: 'Restart VPN',
        description: 'Restart secure-network services and refresh peer routes.',
        tooltip: 'Planned: Restart private-network services and refresh peer routes.',
        displayCommand: 'synergy node vpn restart',
        icon: 'RefreshCw',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.reset-innernet-client',
        label: 'Reset Secure Network',
        description: 'Erase this machine\'s stale sy-vpn client config, service, interface, and Innernet logs without deleting validator keys or chain data.',
        tooltip: 'Use this when the secure validator network says an old sy-vpn config already exists or the VPN needs a clean reconnect. It does not delete your validator keys, wallet, stake, or synced chain data.',
        displayCommand: 'synergy node vpn reset-innernet-client',
        icon: 'PlugZap',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.check-coordinator',
        label: 'Check Coordinator',
        description: 'Check coordinator reachability and current route health.',
        tooltip: 'Planned: See whether the network coordinator can be reached.',
        displayCommand: 'synergy node vpn coordinator status',
        icon: 'RadioTower',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.view-connected-peers',
        label: 'View Connected Peers',
        description: 'Show reachable peer identities and their transport routes.',
        tooltip: 'Planned: See which peers this node can currently reach.',
        displayCommand: 'synergy node peers connected',
        icon: 'Users',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.view-known-peers',
        label: 'Validator Peer Summary',
        description: 'Show connected and status-ready validator peer totals from the local node.',
        tooltip: 'See how many validator peers are connected and how many are sharing current network status.',
        displayCommand: 'synergy node peers summary',
        icon: 'BookOpen',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.refresh-seed-registration',
        label: 'Refresh Validator Peers',
        description: 'Refresh coordinator-signed VPN routes and trusted validator peer targets.',
        tooltip: 'Reload the trusted validator and relayer routes assigned through the secure network without changing your enrollment.',
        displayCommand: 'synergy node peers refresh-validator-routes',
        icon: 'RefreshCw',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.ping-all-peers',
        label: 'Ping All Peers',
        description: 'Measure reachability and latency for connected peers.',
        tooltip: 'Planned: Check reachability and response time for all connected peers.',
        displayCommand: 'synergy node peers ping --all',
        icon: 'Wifi',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.peer-latency-matrix',
        label: 'Peer Latency Matrix',
        description: 'Compare peer latency across available transport routes.',
        tooltip: 'Planned: Compare response times across peer connections.',
        displayCommand: 'synergy node peers latency-matrix',
        icon: 'BarChart3',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.check-routes',
        label: 'Verify VPN Handshake',
        description: 'Confirm that the secure validator network has completed a peer handshake.',
        tooltip: 'Check whether this node has exchanged secure network traffic with another validator peer.',
        displayCommand: 'synergy node vpn handshake',
        icon: 'Route',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.check-dns',
        label: 'Check DNS',
        description: 'Validate DNS resolution for configured network services.',
        tooltip: 'Planned: Check whether required network names resolve correctly.',
        displayCommand: 'synergy node network dns-check',
        icon: 'Globe2',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.check-firewall',
        label: 'Check Firewall',
        description: 'Inspect the host firewall state for required node traffic.',
        tooltip: 'Planned: Check whether the firewall allows required node traffic.',
        displayCommand: 'synergy node firewall check',
        icon: 'ShieldCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.network-vpn.test-port-reachability',
        label: 'Test Port Reachability',
        description: 'Test configured transport ports without changing firewall rules.',
        tooltip: 'Planned: Test network ports without changing firewall settings.',
        displayCommand: 'synergy node ports test',
        icon: 'PlugZap',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'sync-chain-state',
    order: 3,
    label: 'Sync & Chain State',
    description: 'Verify synchronization, finality, and local chain integrity.',
    tooltip: 'Planned tools for checking sync progress and chain health.',
    icon: 'GitBranch',
    accent: '#8b5cf6',
    actions: [
      {
        actionId: 'operations.sync-chain-state.sync-status',
        label: 'Sync Status',
        description: 'Inspect local synchronization progress and lag.',
        tooltip: 'Planned: See how far this node is from the network head.',
        displayCommand: 'synergy node sync status',
        icon: 'Activity',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.verify-chain-state',
        label: 'Inspect Chain State',
        description: 'Inspect local consensus, synchronization, and recent chain evidence.',
        tooltip: 'Read the node\'s current chain and consensus information without changing any data.',
        displayCommand: 'synergy node chain inspect',
        icon: 'ShieldCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.compare-network-head',
        label: 'Compare Network Head',
        description: 'Compare the local head with the current network head.',
        tooltip: 'Planned: Compare this node\'s latest block with the network\'s.',
        displayCommand: 'synergy node chain compare-head',
        icon: 'GitCompare',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.compare-archive-node',
        label: 'Diagnose Sync Sources',
        description: 'Compare the local height with verified network sync sources and explain any gap.',
        tooltip: 'Check which trusted network sources are available and why this node may be behind them.',
        displayCommand: 'synergy node sync diagnose-sources',
        icon: 'Archive',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.finality-status',
        label: 'Finality Status',
        description: 'Inspect the finalized height and finality health.',
        tooltip: 'Planned: See which block is finalized and whether finality is healthy.',
        displayCommand: 'synergy node finality status',
        icon: 'FlagTriangleRight',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.epoch-status',
        label: 'Epoch Status',
        description: 'Inspect the current network epoch and when it changes.',
        tooltip: 'Planned: See the current network period and when it changes.',
        displayCommand: 'synergy node epoch status',
        icon: 'CalendarDays',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.inspect-recent-blocks',
        label: 'Inspect Recent Blocks',
        description: 'Read recent local blocks and the current consensus state without changing node data.',
        tooltip: 'Show the newest blocks this node has received. Use this to confirm that synchronization is still moving forward.',
        displayCommand: 'synergy node chain recent-blocks',
        icon: 'Blocks',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.force-resync',
        label: 'Boost Sync',
        description: 'Refresh trusted sync sources and safely help a lagging node catch up.',
        tooltip: 'Reconnect to trusted sync sources and use guarded recovery when ordinary syncing has stopped making progress.',
        displayCommand: 'synergy node sync boost',
        icon: 'RefreshCw',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.start-normal-sync',
        label: 'Start Normal Sync',
        description: 'Start ordinary peer-based synchronization without applying a snapshot.',
        tooltip: 'Start catching up from connected peers. Activation remains locked until the node is fully synchronized and verified.',
        displayCommand: 'synergy node sync start-normal',
        icon: 'RefreshCcw',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.sync-chain-state.recover-local-fork',
        label: 'Recover Local Fork',
        description: 'Discard only the local diverged chain data and restart peer sync while preserving validator identity, wallet, stake, and VPN enrollment.',
        tooltip: 'Use this when the node is stuck on blocks that do not match the network. It keeps your validator keys, wallet, stake, and secure-network setup, then rebuilds chain data from peers.',
        displayCommand: 'synergy node sync recover-local-fork',
        icon: 'GitPullRequestArrow',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.sync-chain-state.repair-database',
        label: 'Repair Database',
        description: 'Run an approved database repair workflow after confirmation.',
        tooltip: 'Planned: Repair this node\'s local database after confirmation.',
        displayCommand: 'synergy node db repair',
        icon: 'Wrench',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.sync-chain-state.compact-database',
        label: 'Compact Database',
        description: 'Compact local database storage through an approved maintenance workflow.',
        tooltip: 'Planned: Reduce local database storage after confirmation.',
        displayCommand: 'synergy node db compact',
        icon: 'HardDrive',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'snapshots-recovery',
    order: 4,
    label: 'Snapshots & Recovery',
    description: 'Manage verified snapshots, backups, and recovery workflows.',
    tooltip: 'Planned tools for backups, snapshots, and recovering node data.',
    icon: 'Archive',
    accent: '#14b8a6',
    actions: [
      {
        actionId: 'operations.snapshots-recovery.view-snapshots',
        label: 'View Snapshots',
        description: 'List available snapshots and their verification state.',
        tooltip: 'Planned: See available snapshots and whether they are verified.',
        displayCommand: 'synergy node snapshots list',
        icon: 'List',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.download-snapshot',
        label: 'Download Snapshot',
        description: 'Download the latest compatible snapshot for later verification.',
        tooltip: 'Planned: Download the newest snapshot that fits this node.',
        displayCommand: 'synergy node snapshot download --latest-compatible',
        icon: 'Download',
        riskLevel: 'moderate',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.verify-snapshot',
        label: 'Verify Snapshot',
        description: 'Verify snapshot provenance, compatibility, and integrity.',
        tooltip: 'Planned: Check a snapshot\'s source, compatibility, and integrity.',
        displayCommand: 'synergy node snapshot verify',
        icon: 'BadgeCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.apply-snapshot',
        label: 'Download & Apply Snapshot',
        description: 'Download, verify, apply, and synchronize from the latest compatible validator snapshot.',
        tooltip: 'Replace local chain state with the newest compatible signed snapshot, then catch up to the live chain.',
        displayCommand: 'synergy node snapshot download-apply',
        icon: 'FileDown',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.restore-snapshot',
        label: 'Restore Latest Snapshot',
        description: 'Download, verify, and restore the latest compatible validator snapshot.',
        tooltip: 'Replace local chain data with the latest compatible snapshot after automatic verification.',
        displayCommand: 'synergy node snapshot restore --latest-compatible',
        icon: 'ArchiveRestore',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.speed-sync',
        label: 'Speed Sync',
        description: 'Use an approved snapshot-assisted synchronization workflow.',
        tooltip: 'Planned: Use a verified snapshot to help this node catch up.',
        displayCommand: 'synergy node snapshot speed-sync',
        icon: 'Gauge',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.create-local-snapshot',
        label: 'Create Local Snapshot',
        description: 'Create a local recovery snapshot without exposing key material.',
        tooltip: 'Planned: Save a local recovery copy without exposing private keys.',
        displayCommand: 'synergy node snapshot create',
        icon: 'Camera',
        riskLevel: 'moderate',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.backup-config',
        label: 'Backup Config',
        description: 'Create a protected backup of approved node configuration.',
        tooltip: 'Planned: Save a protected copy of this node\'s settings.',
        displayCommand: 'synergy node backup config',
        icon: 'FileArchive',
        riskLevel: 'moderate',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.backup-keys',
        label: 'Backup Keys',
        description: 'Create an encrypted key backup without printing private key material.',
        tooltip: 'Planned: Save an encrypted backup of this node\'s keys.',
        displayCommand: 'synergy node backup keys',
        icon: 'KeyRound',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.restore-backup',
        label: 'Restore Backup',
        description: 'Restore an approved backup after compatibility checks complete.',
        tooltip: 'Planned: Restore a compatible backup to this node.',
        displayCommand: 'synergy node backup restore',
        icon: 'RotateCcw',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.verify-backup',
        label: 'Verify Backup File',
        description: 'Check a selected validator backup for integrity and compatibility without restoring it.',
        tooltip: 'Choose a backup file and check whether it is complete and compatible. This does not change the current node.',
        displayCommand: 'synergy node backup verify',
        icon: 'FileCheck2',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.import-config',
        label: 'Import Configuration',
        description: 'Import a selected validator configuration after compatibility checks.',
        tooltip: 'Choose a compatible configuration backup and apply it to this node. Existing settings may change.',
        displayCommand: 'synergy node config import',
        icon: 'FileInput',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.snapshots-recovery.clean-old-snapshots',
        label: 'Clean Old Snapshots',
        description: 'Remove expired snapshots only after retention checks pass.',
        tooltip: 'Planned: Remove snapshots that are past their retention period.',
        displayCommand: 'synergy node snapshots clean-old',
        icon: 'Trash2',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'staking-rewards',
    order: 8,
    label: 'Staking & Rewards',
    description: 'Review stake, rewards, and wallet-confirmed economic actions.',
    tooltip: 'Planned tools for reviewing stake and managing rewards.',
    icon: 'Coins',
    accent: '#f59e0b',
    actions: [
      {
        actionId: 'operations.staking-rewards.view-stake',
        label: 'View Stake',
        description: 'View current stake and related economic status.',
        tooltip: 'Planned: See how many tokens are staked and their status.',
        displayCommand: 'synergy staking status',
        icon: 'Coins',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.check-account-parity',
        label: 'Check Account Parity',
        description: 'Compare the validator balance and bonded stake reported by the local node against the canonical public RPC.',
        tooltip: 'Use this when the validator wallet or bonded stake looks wrong. It only checks whether the local node and public network agree; it does not move tokens or change stake.',
        displayCommand: 'synergy staking account-parity',
        icon: 'GitCompare',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.staking-rewards.complete-validator-self-bond',
        label: 'Complete Validator Self-Bond',
        description: 'Create the validator\'s exact 50,000 SNRG protocol-locked self-bond from funds already confirmed in the validator account.',
        tooltip: 'Use this after the validator wallet already shows the 50,001 SNRG funding transfer. It bonds exactly 50,000 SNRG from the validator itself and does not ask the owner wallet to send another funding transfer.',
        displayCommand: 'synergy staking self-bond --amount 50000',
        icon: 'ShieldCheck',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        requiresOwnerWallet: true,
        validatorOnly: true,
      },
      {
        actionId: 'operations.staking-rewards.stake-tokens',
        label: 'Stake Tokens',
        description: 'Submit a wallet-confirmed staking request.',
        tooltip: 'Planned: Request staking tokens with wallet confirmation.',
        displayCommand: 'synergy staking stake',
        icon: 'ArrowUpCircle',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.increase-stake',
        label: 'Increase Stake',
        description: 'Submit a wallet-confirmed stake increase request.',
        tooltip: 'Planned: Add to the stake with wallet confirmation.',
        displayCommand: 'synergy staking increase',
        icon: 'CirclePlus',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.unstake-tokens',
        label: 'Unstake Tokens',
        description: 'Submit a wallet-confirmed unstaking request.',
        tooltip: 'Planned: Request unstaking with wallet confirmation.',
        displayCommand: 'synergy staking unstake',
        icon: 'ArrowDownCircle',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.withdraw-unstaked',
        label: 'Withdraw Unstaked',
        description: 'Withdraw eligible unstaked funds after wallet confirmation.',
        tooltip: 'Planned: Withdraw eligible unstaked tokens after confirmation.',
        displayCommand: 'synergy staking withdraw-unstaked',
        icon: 'WalletCards',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.view-rewards',
        label: 'View Rewards',
        description: 'View earned and pending reward information.',
        tooltip: 'Planned: See earned and pending rewards.',
        displayCommand: 'synergy rewards status',
        icon: 'Gift',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.withdraw-rewards',
        label: 'Withdraw Rewards',
        description: 'Withdraw rewards only after a wallet confirmation.',
        tooltip: 'Planned: Withdraw rewards after wallet confirmation.',
        displayCommand: 'synergy rewards withdraw',
        icon: 'Landmark',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.compound-rewards',
        label: 'Compound Rewards',
        description: 'Compound rewards only after a wallet confirmation.',
        tooltip: 'Planned: Add rewards to the stake after wallet confirmation.',
        displayCommand: 'synergy rewards compound',
        icon: 'RefreshCw',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.set-payout-wallet',
        label: 'Set Payout Wallet',
        description: 'Change the payout wallet through a wallet-confirmed request.',
        tooltip: 'Planned: Change where rewards are sent after confirmation.',
        displayCommand: 'synergy rewards payout-wallet set',
        icon: 'Wallet',
        riskLevel: 'critical',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.staking-rewards.export-rewards-csv',
        label: 'Export Rewards CSV',
        description: 'Export reward data in CSV format.',
        tooltip: 'Planned: Save reward information as a CSV file.',
        displayCommand: 'synergy rewards export --format csv',
        icon: 'FileSpreadsheet',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'consensus',
    order: 6,
    label: 'Consensus',
    description: 'Monitor validator consensus and enforce role-aware controls.',
    tooltip: 'Planned tools for checking validator participation and readiness.',
    icon: 'Scale',
    accent: '#d946ef',
    actions: [
      {
        actionId: 'operations.consensus.validator-status',
        label: 'Validator Status',
        description: 'Inspect the selected validator status and consensus readiness.',
        tooltip: 'Planned: See whether this validator is ready for consensus work.',
        displayCommand: 'synergy consensus validator status',
        icon: 'BadgeCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.eligibility-check',
        label: 'Eligibility Check',
        description: 'Check validator eligibility against current consensus requirements.',
        tooltip: 'Planned: Check whether this validator meets consensus requirements.',
        displayCommand: 'synergy consensus eligibility check',
        icon: 'ShieldCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.shadowing-status',
        label: 'Shadowing Status',
        description: 'See whether the validator is observing the network before activation.',
        tooltip: 'Planned: See whether this validator is observing the network before activation.',
        displayCommand: 'synergy consensus shadowing status',
        icon: 'Eye',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.activation-schedule',
        label: 'Activation Schedule',
        description: 'Show when validator activation can next occur.',
        tooltip: 'Planned: See when this validator could next become active.',
        displayCommand: 'synergy consensus activation schedule',
        icon: 'CalendarClock',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.request-validator-rejoin',
        label: 'Request Consensus Rejoin',
        description: 'Arm a guarded validator rejoin request for the next permitted epoch window.',
        tooltip: 'Ask the node to rejoin consensus at the next safe network boundary. This does not bypass synchronization, stake, or eligibility checks.',
        displayCommand: 'synergy consensus rejoin request',
        icon: 'LogIn',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.view-validator-set',
        label: 'View Validator Set',
        description: 'View the current validator set for consensus monitoring.',
        tooltip: 'Planned: See which validators currently participate in consensus.',
        displayCommand: 'synergy consensus validator-set',
        icon: 'Users',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.consensus.participation-report',
        label: 'Participation Report',
        description: 'Review validator participation and duty evidence.',
        tooltip: 'Planned: Review this validator\'s participation and assigned duties.',
        displayCommand: 'synergy consensus participation report',
        icon: 'BarChart3',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.signing-key-status',
        label: 'Signing Key Status',
        description: 'Inspect signing-key health without exposing private material.',
        tooltip: 'Planned: Check the validator signing key without showing its secret.',
        displayCommand: 'synergy consensus signing-key status',
        icon: 'KeyRound',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.missed-attestations',
        label: 'Missed Attestations',
        description: 'Review missed attestations and their recent trend.',
        tooltip: 'Planned: See missed validator attestations and recent changes.',
        displayCommand: 'synergy consensus missed-attestations',
        icon: 'CircleAlert',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.slashing-risk',
        label: 'Slashing Risk',
        description: 'Review current validator slashing-risk indicators.',
        tooltip: 'Planned: Review signs that this validator could be penalized.',
        displayCommand: 'synergy consensus slashing-risk',
        icon: 'ShieldAlert',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: true,
      },
      {
        actionId: 'operations.consensus.request-unjail',
        label: 'Request Unjail',
        description: 'Request validator unjail through a confirmed, signed workflow.',
        tooltip: 'Planned: Request validator reinstatement with a signed confirmation.',
        displayCommand: 'synergy consensus unjail request',
        icon: 'Unlock',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: true,
      },
    ],
  }),
  category({
    id: 'wallet-keys',
    order: 5,
    label: 'Wallet & Keys',
    description: 'Manage wallet connectivity and protected key operations.',
    tooltip: 'Planned tools for wallet connections and protected keys.',
    icon: 'Wallet',
    accent: '#ec4899',
    actions: [
      {
        actionId: 'operations.wallet-keys.wallet-status',
        label: 'Wallet Status',
        description: 'Inspect the connected wallet state and permissions.',
        tooltip: 'Planned: See whether a wallet is connected and what it can approve.',
        displayCommand: 'synergy wallet status',
        icon: 'Wallet',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.connect-wallet',
        label: 'Connect Wallet',
        description: 'Request a wallet connection through the approved integration.',
        tooltip: 'Planned: Connect a wallet through the supported integration.',
        displayCommand: 'synergy wallet connect',
        icon: 'Plug',
        riskLevel: 'moderate',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.verify-owner-wallet',
        label: 'Verify Owner Wallet',
        description: 'Verify the configured owner wallet relationship.',
        tooltip: 'Planned: Check that the connected wallet belongs to this node owner.',
        displayCommand: 'synergy wallet owner verify',
        icon: 'BadgeCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.set-payout-wallet',
        label: 'Set Payout Wallet',
        description: 'Change the payout wallet through a confirmed wallet flow.',
        tooltip: 'Planned: Change where rewards are sent after wallet confirmation.',
        displayCommand: 'synergy rewards payout-wallet set',
        icon: 'Landmark',
        riskLevel: 'critical',
        requiresConfirmation: true,
        requiresWalletConfirmation: true,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.key-status',
        label: 'Key Status',
        description: 'Inspect key availability and protection state without revealing secrets.',
        tooltip: 'Planned: See whether required keys are available and protected.',
        displayCommand: 'synergy keys status',
        icon: 'KeyRound',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.backup-keys',
        label: 'Backup Keys',
        description: 'Create an encrypted key backup without terminal secret output.',
        tooltip: 'Planned: Save an encrypted backup without displaying private keys.',
        displayCommand: 'synergy keys backup',
        icon: 'Archive',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.restore-keys',
        label: 'Restore Keys',
        description: 'Restore protected key material through an approved recovery flow.',
        tooltip: 'Planned: Restore protected keys through the recovery process.',
        displayCommand: 'synergy keys restore',
        icon: 'RotateCcw',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.lock-keystore',
        label: 'Lock Keystore',
        description: 'Lock the local keystore after protected operations complete.',
        tooltip: 'Planned: Lock this node\'s key store after protected work.',
        displayCommand: 'synergy keystore lock',
        icon: 'Lock',
        riskLevel: 'moderate',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.unlock-keystore',
        label: 'Unlock Keystore',
        description: 'Unlock the keystore through the approved protected workflow.',
        tooltip: 'Planned: Unlock this node\'s key store through the protected process.',
        displayCommand: 'synergy keystore unlock',
        icon: 'Unlock',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.wallet-keys.security-audit',
        label: 'Security Audit',
        description: 'Run a non-secret security posture audit.',
        tooltip: 'Planned: Check security settings without exposing secrets.',
        displayCommand: 'synergy security audit',
        icon: 'ShieldCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'logs-diagnostics',
    order: 7,
    label: 'Logs & Diagnostics',
    description: 'Inspect evidence, run diagnostics, and control disk retention.',
    tooltip: 'Planned tools for logs, troubleshooting, and stored diagnostic data.',
    icon: 'Stethoscope',
    accent: '#f97316',
    actions: [
      {
        actionId: 'operations.logs-diagnostics.live-logs',
        label: 'Live Logs',
        description: 'Stream recent node logs through the protected terminal view.',
        tooltip: 'Planned: Watch recent messages from this node.',
        displayCommand: 'synergy logs live',
        icon: 'Terminal',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.search-logs',
        label: 'Search Logs',
        description: 'Search retained logs for relevant diagnostics.',
        tooltip: 'Planned: Find specific messages in saved logs.',
        displayCommand: 'synergy logs search',
        icon: 'Search',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.download-logs',
        label: 'Download Logs',
        description: 'Prepare an approved download of retained logs.',
        tooltip: 'Planned: Save retained logs for review or support.',
        displayCommand: 'synergy logs download',
        icon: 'Download',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.run-diagnostics',
        label: 'Run Diagnostics',
        description: 'Run the standard node diagnostic collection.',
        tooltip: 'Planned: Collect the standard health information for this node.',
        displayCommand: 'synergy diagnostics run',
        icon: 'Stethoscope',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.network-diagnostics',
        label: 'Network Diagnostics',
        description: 'Run read-only diagnostics for network routes and peers.',
        tooltip: 'Planned: Check network paths and peer connections without changes.',
        displayCommand: 'synergy diagnostics network',
        icon: 'Network',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.config-diagnostics',
        label: 'Config Diagnostics',
        description: 'Check configuration health without changing runtime files.',
        tooltip: 'Planned: Check settings for problems without changing them.',
        displayCommand: 'synergy diagnostics config',
        icon: 'FileCheck2',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.security-diagnostics',
        label: 'Security Diagnostics',
        description: 'Run security diagnostics without printing secrets.',
        tooltip: 'Planned: Check security health without displaying secrets.',
        displayCommand: 'synergy diagnostics security',
        icon: 'ShieldCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.rpc-diagnostics',
        label: 'RPC Diagnostics',
        description: 'Test the local node API and summarize which read-only requests respond correctly.',
        tooltip: 'Check whether the local node API is responding to the requests used by the control panel. No settings are changed.',
        displayCommand: 'synergy diagnostics rpc',
        icon: 'Braces',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.dag-status',
        label: 'DAG Status',
        description: 'Inspect the local ordering graph, certificates, and current ordering cut.',
        tooltip: 'Check the node data used to order recent network activity and confirm that it is available.',
        displayCommand: 'synergy diagnostics dag',
        icon: 'GitFork',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.mempool-status',
        label: 'Pending Transactions',
        description: 'Inspect transactions waiting for inclusion in a block.',
        tooltip: 'Show how many transactions are waiting for a block and whether the local transaction queue is responding.',
        displayCommand: 'synergy diagnostics mempool',
        icon: 'ListClock',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.crash-report',
        label: 'Crash Report',
        description: 'Collect available crash-report metadata for investigation.',
        tooltip: 'Planned: Gather crash details to help investigate a problem.',
        displayCommand: 'synergy diagnostics crash-report',
        icon: 'FileWarning',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.export-support-bundle',
        label: 'Export Support Bundle',
        description: 'Create a reviewable support bundle with secret filtering.',
        tooltip: 'Planned: Prepare filtered logs and diagnostics for support.',
        displayCommand: 'synergy diagnostics support-bundle export',
        icon: 'PackageOpen',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.clean-old-logs',
        label: 'Clean Old Logs',
        description: 'Remove expired logs only after retention checks pass.',
        tooltip: 'Planned: Remove logs that are past their retention period.',
        displayCommand: 'synergy logs clean-old',
        icon: 'Trash2',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.logs-diagnostics.clean-old-diagnostics',
        label: 'Clean Old Diagnostics',
        description: 'Remove expired diagnostic artifacts to protect node disk capacity.',
        tooltip: 'Planned: Remove old diagnostic files to free disk space.',
        displayCommand: 'synergy diagnostics clean-old',
        icon: 'Trash',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
  category({
    id: 'updates-maintenance',
    order: 9,
    label: 'Updates & Maintenance',
    description: 'Review releases, perform guarded updates, and maintain host storage.',
    tooltip: 'Planned tools for updates, backups, and host storage maintenance.',
    icon: 'Wrench',
    accent: '#3b82f6',
    actions: [
      {
        actionId: 'operations.updates-maintenance.check-updates',
        label: 'Check Updates',
        description: 'Check whether an approved Control Panel update is available.',
        tooltip: 'Planned: See whether a newer approved Control Panel version is available.',
        displayCommand: 'synergy updates control-panel check',
        icon: 'RefreshCw',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.view-release-notes',
        label: 'View Release Notes',
        description: 'View release notes for the selected update channel.',
        tooltip: 'Planned: Read what changed in the selected update channel.',
        displayCommand: 'synergy updates release-notes',
        icon: 'NotebookText',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.update-runtime',
        label: 'Update Runtime',
        description: 'Install an approved node runtime update after confirmation.',
        tooltip: 'Planned: Install an approved node update after confirmation.',
        displayCommand: 'synergy updates runtime install',
        icon: 'Download',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.update-control-panel',
        label: 'Update Control Panel',
        description: 'Install an approved control panel update after confirmation.',
        tooltip: 'Planned: Install an approved control panel update after confirmation.',
        displayCommand: 'synergy updates control-panel install',
        icon: 'MonitorDown',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.update-cli',
        label: 'Update CLI',
        description: 'Install an approved CLI update after confirmation.',
        tooltip: 'Planned: Install an approved command-line update after confirmation.',
        displayCommand: 'synergy updates cli install',
        icon: 'Terminal',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.run-update-preflight',
        label: 'Run Update Preflight',
        description: 'Verify the node is ready for a guarded update.',
        tooltip: 'Planned: Check whether this node is ready for an update.',
        displayCommand: 'synergy updates preflight',
        icon: 'ClipboardCheck',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.backup-before-update',
        label: 'Backup Before Update',
        description: 'Create an approved backup before applying an update.',
        tooltip: 'Planned: Save an approved backup before an update.',
        displayCommand: 'synergy backup create --before-update',
        icon: 'Archive',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.roll-back-runtime',
        label: 'Roll Back Runtime',
        description: 'Roll back the node runtime through the approved recovery path.',
        tooltip: 'Planned: Return the node runtime to an earlier approved version.',
        displayCommand: 'synergy updates runtime rollback',
        icon: 'RotateCcw',
        riskLevel: 'high',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.disk-analysis',
        label: 'Disk Analysis',
        description: 'Analyze node disk usage and retention pressure.',
        tooltip: 'Planned: See what is using disk space on this node.',
        displayCommand: 'synergy disk analyze',
        icon: 'HardDrive',
        riskLevel: 'safe',
        requiresConfirmation: false,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
      {
        actionId: 'operations.updates-maintenance.clean-temporary-files',
        label: 'Clean Temporary Files',
        description: 'Clean approved temporary files after a retention review.',
        tooltip: 'Planned: Remove approved temporary files after review.',
        displayCommand: 'synergy maintenance clean-temp',
        icon: 'Trash2',
        riskLevel: 'moderate',
        requiresConfirmation: true,
        requiresWalletConfirmation: false,
        validatorOnly: false,
      },
    ],
  }),
];

export const OPERATION_CATEGORIES = Object.freeze(
  [...UNSORTED_OPERATION_CATEGORIES].sort((left, right) => left.order - right.order),
);

export const OPERATION_ACTIONS = Object.freeze(
  OPERATION_CATEGORIES.flatMap((operationCategory) => operationCategory.actions),
);

export const OPERATION_CATEGORY_BY_ID = Object.freeze(
  Object.fromEntries(OPERATION_CATEGORIES.map((operationCategory) => [operationCategory.id, operationCategory])),
);

export const OPERATION_ACTION_BY_ID = Object.freeze(
  Object.fromEntries(OPERATION_ACTIONS.map((action) => [action.actionId, action])),
);

export function getOperationCategory(categoryId) {
  return OPERATION_CATEGORY_BY_ID[categoryId] || null;
}

export function getOperationAction(actionId) {
  return OPERATION_ACTION_BY_ID[actionId] || null;
}
