function firstString(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return '';
}

export const OPERATION_HANDLER_BY_ACTION_ID = Object.freeze({
  'operations.lifecycle.view-status': 'getStatus',
  'operations.lifecycle.start-node': 'start',
  'operations.lifecycle.stop-node': 'stop',
  'operations.lifecycle.restart-node': 'restart',
  'operations.lifecycle.safe-shutdown': 'safeShutdown',
  'operations.lifecycle.emergency-stop': 'emergencyStop',
  'operations.network-vpn.vpn-status': 'vpnStatus',
  'operations.network-vpn.innernet-status': 'innernetStatus',
  'operations.network-vpn.reset-innernet-client': 'resetInnernetClient',
  'operations.network-vpn.check-coordinator': 'coordinatorStatus',
  'operations.network-vpn.view-connected-peers': 'connectedPeers',
  'operations.network-vpn.view-known-peers': 'knownPeers',
  'operations.network-vpn.refresh-seed-registration': 'refreshPeerRegistration',
  'operations.network-vpn.check-routes': 'innernetStatus',
  'operations.network-vpn.test-port-reachability': 'verifyPorts',
  'operations.sync-chain-state.sync-status': 'syncStatus',
  'operations.sync-chain-state.verify-chain-state': 'chainState',
  'operations.sync-chain-state.compare-network-head': 'compareNetworkHead',
  'operations.sync-chain-state.compare-archive-node': 'diagnoseSync',
  'operations.sync-chain-state.finality-status': 'finalityStatus',
  'operations.sync-chain-state.epoch-status': 'epochStatus',
  'operations.sync-chain-state.inspect-recent-blocks': 'recentBlocks',
  'operations.sync-chain-state.force-resync': 'boostSync',
  'operations.sync-chain-state.start-normal-sync': 'startNormalSync',
  'operations.sync-chain-state.recover-local-fork': 'recoverLocalFork',
  'operations.snapshots-recovery.download-snapshot': 'downloadSnapshot',
  'operations.snapshots-recovery.view-snapshots': 'discoverSnapshot',
  'operations.snapshots-recovery.apply-snapshot': 'applyLatestSnapshot',
  'operations.snapshots-recovery.restore-snapshot': 'restoreSnapshot',
  'operations.snapshots-recovery.create-local-snapshot': 'createSnapshot',
  'operations.snapshots-recovery.verify-snapshot': 'verifySnapshot',
  'operations.snapshots-recovery.speed-sync': 'speedSync',
  'operations.snapshots-recovery.backup-config': 'exportConfig',
  'operations.snapshots-recovery.backup-keys': 'backupKeys',
  'operations.snapshots-recovery.restore-backup': 'restoreBackup',
  'operations.snapshots-recovery.verify-backup': 'verifyBackup',
  'operations.snapshots-recovery.import-config': 'importConfig',
  'operations.wallet-keys.key-status': 'keyStatus',
  'operations.wallet-keys.verify-owner-wallet': 'eligibility',
  'operations.wallet-keys.backup-keys': 'backupKeys',
  'operations.wallet-keys.restore-keys': 'restoreBackup',
  'operations.wallet-keys.security-audit': 'securityStatus',
  'operations.consensus.validator-status': 'validatorStatus',
  'operations.consensus.eligibility-check': 'eligibility',
  'operations.consensus.shadowing-status': 'shadowingStatus',
  'operations.consensus.activation-schedule': 'activationSchedule',
  'operations.consensus.request-validator-rejoin': 'requestValidatorRejoin',
  'operations.consensus.view-validator-set': 'activationPreflight',
  'operations.consensus.participation-report': 'participationReport',
  'operations.consensus.signing-key-status': 'signingKeyStatus',
  'operations.consensus.slashing-risk': 'securityStatus',
  'operations.logs-diagnostics.live-logs': 'liveLogs',
  'operations.logs-diagnostics.run-diagnostics': 'healthCheck',
  'operations.logs-diagnostics.network-diagnostics': 'diagnosticsStatus',
  'operations.logs-diagnostics.config-diagnostics': 'configStatus',
  'operations.logs-diagnostics.security-diagnostics': 'securityStatus',
  'operations.logs-diagnostics.rpc-diagnostics': 'rpcDiagnostics',
  'operations.logs-diagnostics.dag-status': 'dagStatus',
  'operations.logs-diagnostics.mempool-status': 'mempoolStatus',
  'operations.logs-diagnostics.export-support-bundle': 'supportBundle',
  'operations.staking-rewards.view-stake': 'stakeReport',
  'operations.staking-rewards.check-account-parity': 'accountStateParity',
  'operations.staking-rewards.complete-validator-self-bond': 'completeValidatorSelfBond',
  'operations.staking-rewards.view-rewards': 'rewardsReport',
  'operations.updates-maintenance.check-updates': 'checkUpdates',
  'operations.updates-maintenance.update-control-panel': 'updateControlPanel',
  'operations.updates-maintenance.run-update-preflight': 'healthCheck',
  'operations.updates-maintenance.backup-before-update': 'createSnapshot',
  'operations.updates-maintenance.disk-analysis': 'storageStatus',
  'operations.updates-maintenance.clean-temporary-files': 'clearNodeCache',
});

export function createOperationHandlers({ service, node, nodeAddress = '', openLogs }) {
  if (!service || typeof service !== 'object') {
    throw new Error('Operations require a node service implementation.');
  }

  const nodeId = node?.id;
  const ownerWalletAddress = firstString(node?.owner_wallet_address, node?.ownerWalletAddress);
  const validatorAddress = firstString(nodeAddress, node?.node_address, node?.nodeAddress);

  return {
    start: () => service.start(nodeId),
    stop: () => service.stop(nodeId),
    restart: () => service.restart(nodeId),
    safeShutdown: () => service.safeShutdown(nodeId),
    emergencyStop: () => service.emergencyStop(nodeId),
    vpnStatus: () => service.getValidatorVpnStatus(nodeId),
    innernetStatus: () => service.getInnernetStatus(nodeId),
    resetInnernetClient: () => service.resetInnernetClientState(),
    coordinatorStatus: () => service.getCoordinatorStatus(nodeId),
    connectedPeers: () => service.getFeatureSnapshot(nodeId, 'diagnostics'),
    knownPeers: () => service.getFeatureSnapshot(nodeId, 'consensus'),
    refreshPeerRegistration: () => service.refreshPeerRegistration(nodeId),
    verifyPorts: () => service.verifyPorts(nodeId),
    boostSync: () => service.boostSync(nodeId),
    speedSync: () => service.speedSync(nodeId),
    diagnoseSync: () => service.diagnoseOnboardingSync(nodeId),
    discoverSnapshot: () => service.discoverValidatorSnapshot(nodeId),
    downloadSnapshot: () => service.downloadValidatorSnapshot(nodeId),
    restoreSnapshot: () => service.restoreValidatorSnapshot(nodeId),
    applyLatestSnapshot: () => service.downloadApplyValidatorSnapshot(nodeId),
    createSnapshot: () => service.createSnapshot(nodeId),
    verifySnapshot: () => service.verifySnapshot(nodeId),
    backupKeys: () => service.backupKeys(nodeId),
    exportConfig: () => service.exportConfig(nodeId),
    restoreBackup: () => service.restoreBackup(nodeId),
    verifyBackup: () => service.verifyBackup(nodeId),
    importConfig: () => service.importConfigForNode(nodeId),
    getStatus: () => service.getStatus(nodeId),
    syncStatus: () => service.getSyncStatus(nodeId),
    chainState: () => service.getFeatureSnapshot(nodeId, 'consensus'),
    compareNetworkHead: () => service.compareNetworkHead(nodeId),
    finalityStatus: () => service.getFinalityStatus(nodeId),
    epochStatus: () => service.getEpochStatus(nodeId),
    recentBlocks: () => service.getRecentBlocks(nodeId, 40),
    startNormalSync: () => service.startNormalSync(nodeId),
    recoverLocalFork: () => service.recoverLocalFork(nodeId),
    keyStatus: () => service.getKeyStatus(nodeId),
    validatorStatus: () => service.getValidatorStatus(nodeId),
    shadowingStatus: () => service.getShadowingStatus(nodeId),
    activationSchedule: () => service.getActivationSchedule(nodeId),
    requestValidatorRejoin: () => service.requestValidatorRejoin(nodeId),
    participationReport: () => service.getParticipationReport(nodeId),
    stakeReport: () => service.getStakeReport(nodeId),
    accountStateParity: () => service.getAccountStateParityReport(nodeId),
    completeValidatorSelfBond: () => service.completeValidatorSelfBond(
      nodeId,
      ownerWalletAddress,
    ),
    rewardsReport: () => service.getRewardsReport(nodeId),
    signingKeyStatus: () => service.getSigningKeyStatus(nodeId),
    eligibility: () => service.verifyValidatorEligibility(
      nodeId,
      ownerWalletAddress,
      validatorAddress,
    ),
    activationPreflight: () => service.getActivationPreflight(nodeId),
    securityStatus: () => service.getFeatureSnapshot(nodeId, 'security'),
    diagnosticsStatus: () => service.getFeatureSnapshot(nodeId, 'diagnostics'),
    configStatus: () => service.getFeatureSnapshot(nodeId, 'config'),
    rpcDiagnostics: () => service.getFeatureSnapshot(nodeId, 'api'),
    dagStatus: () => service.getFeatureSnapshot(nodeId, 'dag'),
    mempoolStatus: () => service.getFeatureSnapshot(nodeId, 'transactions'),
    storageStatus: () => service.getFeatureSnapshot(nodeId, 'storage'),
    rewardsData: () => service.getRewardsData(nodeId),
    healthCheck: () => service.runHealthCheck(nodeId),
    supportBundle: () => service.exportSupportBundle(nodeId),
    liveLogs: async () => {
      const logBundle = await service.getLogs(nodeId, 700);
      if (typeof openLogs === 'function') {
        openLogs();
      }
      return logBundle;
    },
    clearNodeCache: () => service.clearNodeCache(nodeId),
    checkUpdates: () => service.checkForUpdates(),
    updateControlPanel: () => service.update(),
  };
}
