const CHAIN_LOGO_BASE = "https://icons.llamao.fi/icons/chains/rsz_";

const CHAIN_LOGO_OVERRIDES = {
  abstract: "https://icons.llamao.fi/icons/chains/rsz_abstract.jpg",
  algorand: "https://assets.coingecko.com/coins/images/4380/small/download.png",
  aptos: "https://assets.coingecko.com/coins/images/26455/small/aptos_round.png",
  arbitrum: "https://assets.coingecko.com/coins/images/16547/small/arb.jpg",
  aurora: "https://assets.coingecko.com/coins/images/20582/small/aurora.jpeg",
  avalanche: "https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png",
  base: "https://assets.coingecko.com/asset_platforms/images/131/small/base.jpeg",
  berachain: "https://assets.coingecko.com/coins/images/25235/small/BERA.png",
  bitcoin: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png",
  blast: "https://icons.llamao.fi/icons/chains/rsz_blast.jpg",
  blockdag: "https://blockdag.network/images/presskit/Logo.svg",
  bnb: "https://coin-images.coingecko.com/coins/images/825/small/bnb-icon2_2x.png?1696501970",
  bsc: "https://coin-images.coingecko.com/coins/images/825/small/bnb-icon2_2x.png?1696501970",
  cardano: "https://assets.coingecko.com/coins/images/975/small/cardano.png",
  celo: "https://assets.coingecko.com/coins/images/11090/small/InjXBNx9_400x400.jpg",
  celestia: "https://assets.coingecko.com/coins/images/31967/small/tia.jpg",
  cosmos: "https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png",
  cronos: "https://assets.coingecko.com/coins/images/7310/small/cro_token_logo.png",
  ethereum: "https://assets.coingecko.com/coins/images/279/small/ethereum.png",
  filecoin: "https://assets.coingecko.com/coins/images/12817/small/filecoin.png",
  fantom: "https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png",
  fraxtal: "https://assets.coingecko.com/coins/images/13422/small/frax-logo.png",
  gnosis: "https://assets.coingecko.com/coins/images/662/small/logo_square_simple_300px.png",
  ink: "https://icons.llamao.fi/icons/chains/rsz_ink.jpg",
  injective: "https://assets.coingecko.com/coins/images/12882/small/Secondary_Symbol.png",
  kaanch: "https://kaanch.com/logo192.png",
  kava: "https://assets.coingecko.com/coins/images/9761/small/kava.png",
  linea: "https://icons.llamao.fi/icons/chains/rsz_linea.jpg",
  manta: "https://assets.coingecko.com/coins/images/34289/small/manta.jpg",
  mantle: "https://assets.coingecko.com/coins/images/30980/small/token-logo.png",
  metis: "https://assets.coingecko.com/coins/images/15595/small/Metis_Black_Bg.png",
  mode: "https://assets.coingecko.com/coins/images/34979/small/MODE.jpg",
  moonriver: "https://assets.coingecko.com/coins/images/17984/small/9285.png",
  moonbeam: "https://assets.coingecko.com/coins/images/22459/small/glmr.png",
  canto: "https://assets.coingecko.com/coins/images/26959/small/canto-network.png",
  boba: "https://assets.coingecko.com/coins/images/20285/small/BOBA.png",
  opbnb: "https://coin-images.coingecko.com/coins/images/825/small/bnb-icon2_2x.png?1696501970",
  optimism: "https://assets.coingecko.com/coins/images/25244/small/Optimism.png",
  osmosis: "https://assets.coingecko.com/coins/images/16724/small/osmo.png",
  polkadot: "https://assets.coingecko.com/coins/images/12171/small/polkadot.png",
  polygon: "https://assets.coingecko.com/coins/images/32440/small/polygon.png",
  "polygon-zkevm": "https://assets.coingecko.com/coins/images/32440/small/polygon.png",
  polygonzkevm: "https://assets.coingecko.com/coins/images/32440/small/polygon.png",
  rootstock: "https://assets.coingecko.com/coins/images/5070/small/RBTC-logo.png",
  scroll: "https://icons.llamao.fi/icons/chains/rsz_scroll.jpg",
  sei: "https://assets.coingecko.com/coins/images/28205/small/Sei_Logo_-_Transparent.png",
  solana: "https://assets.coingecko.com/coins/images/4128/small/solana.png",
  sonic: "https://assets.coingecko.com/coins/images/38108/small/200x200_Sonic_Logo.png",
  sui: "https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg",
  taiko: "https://icons.llamao.fi/icons/chains/rsz_taiko.jpg",
  ton: "https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png",
  tron: "https://assets.coingecko.com/coins/images/1094/small/tron-logo.png",
  unichain: "https://assets.coingecko.com/coins/images/12504/small/uniswap-logo.png",
  worldchain: "https://assets.coingecko.com/coins/images/31069/small/worldcoin.jpeg",
  xlayer: "https://assets.coingecko.com/coins/images/4463/small/okb_token.png",
  xrp: "https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png",
  zircuit: "https://icons.llamao.fi/icons/chains/rsz_zircuit.jpg",
  "zksync-era": "https://assets.coingecko.com/coins/images/38043/small/ZKTokenBlack.png",
  zksync: "https://assets.coingecko.com/coins/images/38043/small/ZKTokenBlack.png",
};

export function chainLogo(slug) {
  const normalized = String(slug || "").trim().toLowerCase();
  return CHAIN_LOGO_OVERRIDES[normalized] || `${CHAIN_LOGO_BASE}${normalized}.jpg`;
}
