#!/usr/bin/env bash
set -euo pipefail

TEMPLATE=${1:-/etc/synergy/validator/config.toml.example}
OUTPUT=${2:-/etc/synergy/validator/config.toml}
: "${SYNERGY_VALIDATOR_NAME:?set SYNERGY_VALIDATOR_NAME}"
: "${SYNERGY_VALIDATOR_INDEX:?set SYNERGY_VALIDATOR_INDEX}"
: "${SYNERGY_VALIDATOR_ADDRESS:?set SYNERGY_VALIDATOR_ADDRESS}"
: "${SYNERGY_PUBLIC_IP:?set SYNERGY_PUBLIC_IP}"
: "${SYNERGY_PRIVATE_IP:?set SYNERGY_PRIVATE_IP}"
: "${SYNERGY_PEER_ID:?set SYNERGY_PEER_ID}"

sed \
  -e "s/CHANGE_ME_VALIDATOR_NAME/${SYNERGY_VALIDATOR_NAME}/g" \
  -e "s/CHANGE_ME_VALIDATOR_INDEX/${SYNERGY_VALIDATOR_INDEX}/g" \
  -e "s/CHANGE_ME_VALIDATOR_ADDRESS/${SYNERGY_VALIDATOR_ADDRESS}/g" \
  -e "s/CHANGE_ME_PUBLIC_IP/${SYNERGY_PUBLIC_IP}/g" \
  -e "s/CHANGE_ME_PRIVATE_IP/${SYNERGY_PRIVATE_IP}/g" \
  -e "s/CHANGE_ME_PEER_ID/${SYNERGY_PEER_ID}/g" \
  "$TEMPLATE" > "$OUTPUT"

