import {
  abstract,
  arbitrum,
  aurora,
  avalanche,
  base,
  celo,
  berachain,
  blast,
  bsc,
  cronos,
  filecoin,
  fraxtal,
  gnosis,
  ink,
  kava,
  linea,
  mainnet,
  manta,
  mantle,
  mode,
  metis,
  moonbeam,
  opBNB,
  optimism,
  polygon,
  polygonZkEvm,
  rootstock,
  sei,
  scroll,
  sonic,
  taiko,
  unichain,
  worldchain,
  xLayer,
  zircuit,
  zksync,
} from "wagmi/chains";

function trimTrailingSlash(value) {
  return String(value || "").replace(/\/+$/, "");
}

function createChainDefinition({
  chain,
  id,
  name,
  label,
  short,
  accent,
  logoURI,
  swapSupported = false,
}) {
  const explorerUrl = chain.blockExplorers?.default?.url ? trimTrailingSlash(chain.blockExplorers.default.url) : "";
  return {
    id,
    chain,
    chainId: chain.id,
    name: name || chain.name,
    label: label || name || chain.name,
    short,
    accent,
    color: accent,
    logoURI,
    nativeCurrency: chain.nativeCurrency,
    nativeSymbol: chain.nativeCurrency?.symbol || short,
    publicRpcUrl: chain.rpcUrls?.default?.http?.[0] || "",
    explorerTxBase: explorerUrl ? `${explorerUrl}/tx/` : "",
    swapSupported,
  };
}

export const EVM_CHAIN_DEFINITIONS = [
  createChainDefinition({
    chain: mainnet,
    id: "ethereum",
    name: "Ethereum Mainnet",
    label: "Ethereum Mainnet",
    short: "ETH",
    accent: "#627eea",
    logoURI: "https://assets.coingecko.com/coins/images/279/small/ethereum.png",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: arbitrum,
    id: "arbitrum",
    name: "Arbitrum One",
    label: "Arbitrum One",
    short: "ARB",
    accent: "#28a0f0",
    logoURI: "https://assets.coingecko.com/coins/images/16547/small/arb.jpg",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: base,
    id: "base",
    name: "Base",
    label: "Base",
    short: "BAS",
    accent: "#0052ff",
    logoURI: "https://assets.coingecko.com/asset_platforms/images/131/small/base.jpeg",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: optimism,
    id: "optimism",
    name: "Optimism",
    label: "Optimism",
    short: "OP",
    accent: "#ff0420",
    logoURI: "https://assets.coingecko.com/coins/images/25244/small/Optimism.png",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: polygon,
    id: "polygon",
    name: "Polygon PoS",
    label: "Polygon PoS",
    short: "POL",
    accent: "#8247e5",
    logoURI: "https://assets.coingecko.com/coins/images/4713/small/polygon.png",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: avalanche,
    id: "avalanche",
    name: "Avalanche C-Chain",
    label: "Avalanche C-Chain",
    short: "AVA",
    accent: "#e84142",
    logoURI: "https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: bsc,
    id: "bsc",
    name: "BNB Smart Chain",
    label: "BNB Smart Chain",
    short: "BSC",
    accent: "#f0b90b",
    logoURI: "https://coin-images.coingecko.com/coins/images/825/small/bnb-icon2_2x.png?1696501970",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: gnosis,
    id: "gnosis",
    name: "Gnosis Chain",
    label: "Gnosis Chain",
    short: "GNO",
    accent: "#48a9a6",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: cronos,
    id: "cronos",
    name: "Cronos Mainnet",
    label: "Cronos",
    short: "CRO",
    accent: "#002d74",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: moonbeam,
    id: "moonbeam",
    name: "Moonbeam",
    label: "Moonbeam",
    short: "GLMR",
    accent: "#6b7cff",
  }),
  createChainDefinition({
    chain: celo,
    id: "celo",
    name: "Celo",
    label: "Celo",
    short: "CELO",
    accent: "#35d07f",
  }),
  createChainDefinition({
    chain: kava,
    id: "kava",
    name: "Kava EVM",
    label: "Kava",
    short: "KAVA",
    accent: "#ff6b35",
  }),
  createChainDefinition({
    chain: metis,
    id: "metis",
    name: "Metis",
    label: "Metis",
    short: "MET",
    accent: "#00a3ff",
  }),
  createChainDefinition({
    chain: aurora,
    id: "aurora",
    name: "Aurora",
    label: "Aurora",
    short: "AUR",
    accent: "#7c3aed",
  }),
  createChainDefinition({
    chain: rootstock,
    id: "rootstock",
    name: "Rootstock Mainnet",
    label: "Rootstock",
    short: "RSK",
    accent: "#f7931a",
  }),
  createChainDefinition({
    chain: opBNB,
    id: "opbnb",
    name: "opBNB",
    label: "opBNB",
    short: "OPB",
    accent: "#f0b90b",
  }),
  createChainDefinition({
    chain: sonic,
    id: "sonic",
    name: "Sonic",
    label: "Sonic",
    short: "SON",
    accent: "#0ea5e9",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: linea,
    id: "linea",
    name: "Linea Mainnet",
    label: "Linea",
    short: "LIN",
    accent: "#1d4ed8",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: zksync,
    id: "zksync",
    name: "ZKsync Era",
    label: "ZKsync Era",
    short: "ZK",
    accent: "#8a5cff",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: scroll,
    id: "scroll",
    name: "Scroll",
    label: "Scroll",
    short: "SCR",
    accent: "#f97316",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: polygonZkEvm,
    id: "polygonZkEvm",
    name: "Polygon zkEVM",
    label: "Polygon zkEVM",
    short: "ZKE",
    accent: "#8247e5",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: taiko,
    id: "taiko",
    name: "Taiko Mainnet",
    label: "Taiko",
    short: "TAI",
    accent: "#2d1b69",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: blast,
    id: "blast",
    name: "Blast",
    label: "Blast",
    short: "BLA",
    accent: "#f59e0b",
  }),
  createChainDefinition({
    chain: mode,
    id: "mode",
    name: "Mode Mainnet",
    label: "Mode",
    short: "MOD",
    accent: "#7c3aed",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: manta,
    id: "manta",
    name: "Manta Pacific Mainnet",
    label: "Manta Pacific",
    short: "MAN",
    accent: "#14b8a6",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: mantle,
    id: "mantle",
    name: "Mantle",
    label: "Mantle",
    short: "MNT",
    accent: "#4ade80",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: fraxtal,
    id: "fraxtal",
    name: "Fraxtal",
    label: "Fraxtal",
    short: "FRX",
    accent: "#00bcd4",
  }),
  createChainDefinition({
    chain: berachain,
    id: "berachain",
    name: "Berachain",
    label: "Berachain",
    short: "BER",
    accent: "#f97316",
  }),
  createChainDefinition({
    chain: unichain,
    id: "unichain",
    name: "Unichain",
    label: "Unichain",
    short: "UCH",
    accent: "#ff007a",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: worldchain,
    id: "worldchain",
    name: "World Chain",
    label: "World Chain",
    short: "WLD",
    accent: "#3b82f6",
  }),
  createChainDefinition({
    chain: ink,
    id: "ink",
    name: "Ink",
    label: "Ink",
    short: "INK",
    accent: "#2563eb",
  }),
  createChainDefinition({
    chain: abstract,
    id: "abstract",
    name: "Abstract",
    label: "Abstract",
    short: "ABS",
    accent: "#f59e0b",
  }),
  createChainDefinition({
    chain: sei,
    id: "sei",
    name: "Sei Network",
    label: "Sei",
    short: "SEI",
    accent: "#ff4d4f",
  }),
  createChainDefinition({
    chain: zircuit,
    id: "zircuit",
    name: "Zircuit Mainnet",
    label: "Zircuit",
    short: "ZRC",
    accent: "#7c3aed",
  }),
  createChainDefinition({
    chain: xLayer,
    id: "xLayer",
    name: "X Layer Mainnet",
    label: "X Layer",
    short: "OKB",
    accent: "#1d4ed8",
    swapSupported: true,
  }),
  createChainDefinition({
    chain: filecoin,
    id: "filecoin",
    name: "Filecoin Mainnet",
    label: "Filecoin EVM",
    short: "FIL",
    accent: "#0090ff",
  }),
];

export const EVM_CHAIN_IDS = EVM_CHAIN_DEFINITIONS.map((definition) => definition.chainId);
export const EVM_SWAP_CHAIN_IDS = EVM_CHAIN_DEFINITIONS.filter((definition) => definition.swapSupported).map((definition) => definition.chainId);
export const EVM_WALLET_CHAINS = EVM_CHAIN_DEFINITIONS.map((definition) => definition.chain);

export function getEvmChainDefinition(chainId) {
  return EVM_CHAIN_DEFINITIONS.find((definition) => definition.chainId === Number(chainId)) || null;
}
