# Generated Testnet-v3 Genesis binding. Do not hand-edit.
[Service]
Environment=SYNERGY_GENESIS_FILE=/etc/synergy/testnet-v3/genesis.json
Environment=SYNERGY_GENESIS_SHA256=ee554c197a878cbfdaf7d470a0274ab2859a7a0c14c87e425908a69c6fbb51cf
Environment=SYNERGY_GENESIS_HASH=c087b6b7c1aae6f13f4c0140ba9a230a12dea0fa52b611777dee69369457de3d
