#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INVENTORY_FILE="$ROOT_DIR/testnet/runtime/node-inventory.csv"
OUTPUT_FILE="${1:-$ROOT_DIR/testnet/runtime/hosts.env}"
ORCHESTRATOR_SCRIPT="$ROOT_DIR/scripts/testnet/remote-node-orchestrator.sh"
KEYS_DIR="$ROOT_DIR/testnet/runtime/keys"
TESTNET_ENV_DIR_DEFAULT="${TESTNET_ENV_DIR_DEFAULT:-$ROOT_DIR/testnet/runtime/env-files}"
ENV_OVERRIDE_HELPER="${ENV_OVERRIDE_HELPER:-$ROOT_DIR/../scripts/testnet/testnet-env-overrides.sh}"

if [[ -f "$ENV_OVERRIDE_HELPER" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_OVERRIDE_HELPER"
fi

if [[ ! -f "$INVENTORY_FILE" ]]; then
  echo "Inventory file missing: $INVENTORY_FILE" >&2
  exit 1
fi

if [[ ! -x "$ORCHESTRATOR_SCRIPT" ]]; then
  echo "Orchestrator script missing or not executable: $ORCHESTRATOR_SCRIPT" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
if [[ -f "$OUTPUT_FILE" ]]; then
  backup="$OUTPUT_FILE.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$OUTPUT_FILE" "$backup"
  echo "Backed up existing hosts.env to: $backup"
fi

cat > "$OUTPUT_FILE" <<HEADER
# Auto-generated by scripts/testnet/generate-monitor-hosts-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file powers the Synergy Node Control Panel app remote orchestration workflow.
#
# Global SSH defaults used by remote-node-orchestrator.sh:
SYNERGY_TESTNET_SSH_USER=ops
SYNERGY_TESTNET_SSH_PORT=22
# Optional global SSH private key path:
# SYNERGY_TESTNET_SSH_KEY=/Users/you/.ssh/id_ed25519

# Explorer bridge used by control panel Atlas links:
ATLAS_BASE_URL=https://testnet-explorer.synergy-network.io
SYNERGY_EXPLORER_RESET_ENDPOINT=https://testnet-atlas-api.synergy-network.io/v1/admin/reindex-from-genesis

HEADER

while IFS=, read -r node_slot_id node_alias role_group role node_type _ _ _ _ _ _ host management_host _ _ _ _ _ _ _ public_ip local_ip || [[ -n "${node_slot_id:-}" ]]; do
  [[ "$node_slot_id" == "node_slot_id" ]] && continue
  [[ -z "${node_slot_id:-}" ]] && continue

  validator_address=""
  if [[ -f "$KEYS_DIR/${node_slot_id}/address.txt" ]]; then
    validator_address="$(cat "$KEYS_DIR/${node_slot_id}/address.txt")"
  fi

  resolved_host="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$host" "HOSTNAME" "$host")"
  resolved_public_ip="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "PUBLIC_IP" "$public_ip")"
  resolved_local_ip="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "LOCAL_IP" "$local_ip")"
  resolved_management_host="$(testnet_first_nonempty \
    "$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "MANAGEMENT_HOST" "")" \
    "$resolved_public_ip" \
    "$resolved_local_ip" \
    "$management_host" \
    "$resolved_host" \
  )"
  resolved_ssh_user="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "SSH_USER" "ops")"
  resolved_ssh_port="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "SSH_PORT" "22")"
  resolved_ssh_key="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "SSH_KEY" "")"
  resolved_remote_dir="$(testnet_inventory_env_value "$node_slot_id" "$node_type" "$validator_address" "$resolved_host" "REMOTE_DIR" "")"
  node_slot_key="$(printf '%s' "$node_slot_id" | tr '[:lower:]-' '[:upper:]_')"

  cat >> "$OUTPUT_FILE" <<ENTRY
# -----------------------------------------------------------------------------
# $node_slot_id ($node_alias | $role_group | $role | $node_type)
${node_slot_key}_HOST=$resolved_host
${node_slot_key}_PUBLIC_IP=$resolved_public_ip
${node_slot_key}_MANAGEMENT_HOST=$resolved_management_host
${node_slot_key}_SSH_USER=$resolved_ssh_user
${node_slot_key}_SSH_PORT=$resolved_ssh_port
${node_slot_key}_SSH_KEY=$resolved_ssh_key
${node_slot_key}_REMOTE_DIR=$resolved_remote_dir

${node_slot_key}_START_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id start"
${node_slot_key}_STOP_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id stop"
${node_slot_key}_RESTART_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id restart"
${node_slot_key}_STATUS_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id status"
${node_slot_key}_SETUP_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id setup_node"
${node_slot_key}_EXPORT_LOGS_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id export_logs"
${node_slot_key}_VIEW_CHAIN_DATA_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id view_chain_data"
${node_slot_key}_EXPORT_CHAIN_DATA_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id export_chain_data"

${node_slot_key}_ACTION_INSTALL_NODE_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id install_node"
${node_slot_key}_ACTION_BOOTSTRAP_NODE_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id bootstrap_node"
${node_slot_key}_ACTION_NODE_LOGS_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id logs"
${node_slot_key}_ACTION_RESET_CHAIN_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id reset_chain"

ENTRY

done < "$INVENTORY_FILE"

echo "Generated monitor hosts config: $OUTPUT_FILE"
