#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INVENTORY_FILE="$ROOT_DIR/testnet/runtime/node-inventory.csv"
OUTPUT_FILE="${1:-$ROOT_DIR/testnet/runtime/hosts.env}"
ORCHESTRATOR_SCRIPT="$ROOT_DIR/scripts/testnet/remote-node-orchestrator.sh"

if [[ ! -f "$INVENTORY_FILE" ]]; then
  echo "Inventory file missing: $INVENTORY_FILE" >&2
  exit 1
fi

if [[ ! -x "$ORCHESTRATOR_SCRIPT" ]]; then
  echo "Orchestrator script missing or not executable: $ORCHESTRATOR_SCRIPT" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
if [[ -f "$OUTPUT_FILE" ]]; then
  backup="$OUTPUT_FILE.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$OUTPUT_FILE" "$backup"
  echo "Backed up existing hosts.env to: $backup"
fi

cat > "$OUTPUT_FILE" <<HEADER
# Auto-generated by scripts/testnet/generate-monitor-hosts-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file powers the Testnet Node Monitor app remote orchestration workflow.
#
# Global SSH defaults used by remote-node-orchestrator.sh:
SYNERGY_TESTNET_SSH_USER=ops
SYNERGY_TESTNET_SSH_PORT=22
# Optional global SSH private key path:
# SYNERGY_TESTNET_SSH_KEY=/Users/you/.ssh/id_ed25519
# Explorer bridge used by node monitor Atlas links:
ATLAS_BASE_URL=https://testnet-explorer.synergy-network.io

HEADER

while IFS=, read -r machine_id node_id role_group role node_type _ _ _ _ _ _ host management_host _ _ _ || [[ -n "${machine_id:-}" ]]; do
  [[ "$machine_id" == "machine_id" ]] && continue
  [[ -z "${machine_id:-}" ]] && continue

  machine_key="$(printf '%s' "$machine_id" | tr '[:lower:]-' '[:upper:]_')"

  if [[ -z "${host:-}" ]]; then
    host="$management_host"
  fi

  cat >> "$OUTPUT_FILE" <<ENTRY
# -----------------------------------------------------------------------------
# $machine_id ($node_id | $role_group | $role | $node_type)
${machine_key}_HOST=$host
${machine_key}_MANAGEMENT_HOST=$management_host
${machine_key}_SSH_USER=ops
${machine_key}_SSH_PORT=22
# ${machine_key}_SSH_KEY=
# ${machine_key}_REMOTE_DIR=/opt/synergy/$machine_id
${machine_key}_START_CMD="$ORCHESTRATOR_SCRIPT $machine_id start"
${machine_key}_STOP_CMD="$ORCHESTRATOR_SCRIPT $machine_id stop"
${machine_key}_RESTART_CMD="$ORCHESTRATOR_SCRIPT $machine_id restart"
${machine_key}_STATUS_CMD="$ORCHESTRATOR_SCRIPT $machine_id status"
${machine_key}_SETUP_CMD="$ORCHESTRATOR_SCRIPT $machine_id setup_node"
${machine_key}_EXPORT_LOGS_CMD="$ORCHESTRATOR_SCRIPT $machine_id export_logs"
${machine_key}_VIEW_CHAIN_DATA_CMD="$ORCHESTRATOR_SCRIPT $machine_id view_chain_data"
${machine_key}_EXPORT_CHAIN_DATA_CMD="$ORCHESTRATOR_SCRIPT $machine_id export_chain_data"

${machine_key}_ACTION_INSTALL_NODE_CMD="$ORCHESTRATOR_SCRIPT $machine_id install_node"
${machine_key}_ACTION_BOOTSTRAP_NODE_CMD="$ORCHESTRATOR_SCRIPT $machine_id bootstrap_node"
${machine_key}_ACTION_NODE_LOGS_CMD="$ORCHESTRATOR_SCRIPT $machine_id logs"
${machine_key}_ACTION_RESET_CHAIN_CMD="$ORCHESTRATOR_SCRIPT $machine_id reset_chain"

ENTRY

done < "$INVENTORY_FILE"

echo "Generated monitor hosts config: $OUTPUT_FILE"
