server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: synergy-node-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: synergy-node
          __path__: /var/log/synergy/*/logs/*.log
    relabel_configs:
      - source_labels: [__path__]
        regex: /var/log/synergy/([^/]+)/logs/.*
        target_label: machine

  - job_name: synergy-node-out
    static_configs:
      - targets:
          - localhost
        labels:
          job: synergy-node-out
          __path__: /var/log/synergy/*/logs/node.out
    relabel_configs:
      - source_labels: [__path__]
        regex: /var/log/synergy/([^/]+)/logs/.*
        target_label: machine

  - job_name: monitoring-host-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: host-system
          __path__: /var/log/host/*.log
