#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EtdagError {
    UnsupportedProfile,
    InvalidTargetOffset,
    InvalidCapacity,
    InvalidCiphertextClasses,
    ContextMismatch,
    EmptyCiphertext,
    DuplicateEnvelope,
    AdmissionClosed,
    AdmissionCapacity,
    DuplicateOrderKey,
    InvalidDigest,
    InvalidEnvelope(String),
    UnknownParent(String),
    DuplicateVertex(String),
    Cycle,
    InsufficientAvailability { signed: usize, required: usize },
    UnauthorizedReveal,
    DuplicateShare(String),
    InvalidExecutionInput,
    InvalidSignature,
    UnauthorizedValidator(String),
    Replay(String),
    RateLimited,
    ConflictingArtifact(String),
    MissingArtifact(String),
    Governance(String),
    RevealThreshold { collected: usize, required: usize },
    Storage(String),
    Corrupt(String),
}
