use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use synergy_protocol_types::NodeRole;

use crate::{
    ConsensusConfiguration, EtdagConfiguration, NetworkConfiguration, P2pConfiguration,
    RpcConfiguration, StorageConfiguration, TelemetryConfiguration, VpnConfiguration,
};

pub const CONFIG_SCHEMA_VERSION: u16 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NodeConfiguration {
    pub schema_version: u16,
    pub node_name: String,
    pub role: NodeRole,
    pub chain_id: u64,
    pub network_id: String,
    /// Signed new-network context used to bind transport, sync, and PoSy
    /// callers to one chain incarnation. Legacy Genesis formats are excluded.
    pub manifest_path: PathBuf,
    pub public_identity_path: PathBuf,
    /// Optional governed Aegis identity-to-public-key bindings for P2P authentication.
    #[serde(default)]
    pub aegis_key_bindings_path: Option<PathBuf>,
    /// Provisioned local P2P identity signing key; never generated by the node.
    #[serde(default)]
    pub aegis_signing_key_path: Option<PathBuf>,
    pub admin_socket_path: PathBuf,
    #[serde(default)]
    pub network: NetworkConfiguration,
    #[serde(default)]
    pub p2p: P2pConfiguration,
    #[serde(default)]
    pub consensus: ConsensusConfiguration,
    #[serde(default)]
    pub etdag: EtdagConfiguration,
    pub storage: StorageConfiguration,
    #[serde(default)]
    pub rpc: RpcConfiguration,
    #[serde(default)]
    pub telemetry: TelemetryConfiguration,
    #[serde(default)]
    pub vpn: VpnConfiguration,
}
