use clap::{Parser, Subcommand};
use pqsynq::{
    canonicalize_signing_payload, derive_synq_address, hash_contract_call_body,
    hash_contract_deploy_body, AegisSynQVerifier, AlgorithmId, ChainId, ContractCallEnvelope,
    ContractDeployEnvelope, DigitalSignature, DomainTag, NetworkId, Sign, SignaturePurpose,
    SynQAddress, SynQPublicKey, SynQSignature, SynQSigningPayload, VerificationContext,
};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Creates a minimal SynQ project scaffold
    Init {
        /// Project directory to create
        name: PathBuf,
        /// Overwrite existing scaffold files if they already exist
        #[arg(long, default_value_t = false)]
        force: bool,
    },
    /// Builds canonical SynQ bytecode, ABI, manifest, and compatibility artifacts
    Build {
        /// The path to the SynQ source file
        path: PathBuf,
    },
    /// Checks parsing, semantic analysis, bytecode generation, ABI, and manifest generation
    Check {
        /// The path to the SynQ source file
        path: PathBuf,
    },
    /// Emits the deterministic ABI artifact for a SynQ source file
    Abi {
        /// The path to the SynQ source file
        path: PathBuf,
        /// Optional output file. Prints to stdout when omitted.
        #[arg(short, long)]
        output: Option<PathBuf>,
    },
    /// Emits the deterministic manifest artifact for a SynQ source file
    Manifest {
        /// The path to the SynQ source file
        path: PathBuf,
        /// Optional output file. Prints to stdout when omitted.
        #[arg(short, long)]
        output: Option<PathBuf>,
    },
    /// Generates a local testnet ML-DSA-87 keypair through aegis-pqsynq
    Keygen {
        /// Signature algorithm. Launch policy currently supports ml-dsa-65 only.
        #[arg(long, default_value = "ml-dsa-87")]
        algorithm: String,
        /// Network profile. Accepts testnet, synergy-testnet, or synergy-testnet-v3.
        #[arg(long, default_value = "testnet")]
        network: String,
        /// Output directory for key material.
        #[arg(long, default_value = "keys")]
        out_dir: PathBuf,
        /// File stem for generated key files.
        #[arg(long, default_value = "synq-testnet-mldsa65")]
        name: String,
        /// Overwrite existing key files.
        #[arg(long, default_value_t = false)]
        force: bool,
    },
    /// Signs a SynQ deploy envelope through aegis-pqsynq without submitting it
    SignDeploy {
        /// Compiled SynQ bytecode artifact.
        #[arg(long)]
        bytecode: PathBuf,
        /// SynQ manifest JSON artifact.
        #[arg(long)]
        manifest: PathBuf,
        /// SynQ ABI JSON artifact.
        #[arg(long)]
        abi: PathBuf,
        /// Private key JSON generated by `synq keygen`.
        #[arg(long = "private-key")]
        private_key: PathBuf,
        /// Constructor arguments as a JSON array.
        #[arg(long)]
        args: Option<String>,
        /// Output file for the signed ContractDeployEnvelope JSON.
        #[arg(short, long)]
        output: PathBuf,
        /// Chain ID for the signing payload.
        #[arg(long, default_value_t = 1266)]
        chain: u64,
        /// Network ID for the signing payload.
        #[arg(long, default_value = "synergy-testnet")]
        network: String,
        /// Replay nonce.
        #[arg(long, default_value_t = 1)]
        nonce: u64,
        /// Optional not-before timestamp.
        #[arg(long = "not-before-unix", default_value_t = 0)]
        not_before_unix: u64,
        /// Expiration timestamp.
        #[arg(long = "expiration-unix", default_value_t = 4_102_444_800)]
        expiration_unix: u64,
        /// Overwrite an existing envelope file.
        #[arg(long, default_value_t = false)]
        force: bool,
    },
    /// Verifies a signed SynQ deploy envelope through aegis-pqsynq
    VerifyDeploy {
        /// Signed ContractDeployEnvelope JSON.
        envelope: PathBuf,
        /// Chain ID expected by the verifier context.
        #[arg(long, default_value_t = 1266)]
        chain: u64,
        /// Network ID expected by the verifier context.
        #[arg(long, default_value = "synergy-testnet")]
        network: String,
        /// Current timestamp for expiration checks.
        #[arg(long = "now-unix", default_value_t = 1_800_000_000)]
        now_unix: u64,
    },
    /// Signs a SynQ contract-call envelope through aegis-pqsynq without submitting it
    SignCall {
        /// Contract address. Accepts `tsynq1...` debug form or raw address hex.
        #[arg(long)]
        contract: String,
        /// Method name from the ABI. Current CLI call signing supports no-argument methods.
        #[arg(long)]
        method: String,
        /// SynQ ABI JSON artifact.
        #[arg(long)]
        abi: PathBuf,
        /// SynQ manifest JSON artifact.
        #[arg(long)]
        manifest: PathBuf,
        /// Private key JSON generated by `synq keygen`.
        #[arg(long = "private-key")]
        private_key: PathBuf,
        /// JSON args. Current no-argument call subset accepts omitted, empty, or `[]`.
        #[arg(long)]
        args: Option<String>,
        /// Output file for the signed ContractCallEnvelope JSON.
        #[arg(short, long)]
        output: PathBuf,
        /// Chain ID for the signing payload.
        #[arg(long, default_value_t = 1266)]
        chain: u64,
        /// Network ID for the signing payload.
        #[arg(long, default_value = "synergy-testnet")]
        network: String,
        /// Replay nonce.
        #[arg(long, default_value_t = 1)]
        nonce: u64,
        /// Optional not-before timestamp.
        #[arg(long = "not-before-unix", default_value_t = 0)]
        not_before_unix: u64,
        /// Expiration timestamp.
        #[arg(long = "expiration-unix", default_value_t = 4_102_444_800)]
        expiration_unix: u64,
        /// Overwrite an existing envelope file.
        #[arg(long, default_value_t = false)]
        force: bool,
    },
    /// Verifies a signed SynQ call envelope through aegis-pqsynq
    VerifyCall {
        /// Signed ContractCallEnvelope JSON.
        envelope: PathBuf,
        /// Chain ID expected by the verifier context.
        #[arg(long, default_value_t = 1266)]
        chain: u64,
        /// Network ID expected by the verifier context.
        #[arg(long, default_value = "synergy-testnet")]
        network: String,
        /// Current timestamp for expiration checks.
        #[arg(long = "now-unix", default_value_t = 1_800_000_000)]
        now_unix: u64,
    },
    /// Locally simulates generated SynQ bytecode through the current QuantumVM
    Simulate {
        /// The path to the SynQ source file
        path: PathBuf,
    },
    /// Compiles a SynQ source file
    Compile {
        /// The path to the SynQ source file
        #[arg(short, long)]
        path: PathBuf,
    },
    /// Runs a compiled SynQ bytecode file
    Run {
        /// The path to the SynQ bytecode file
        #[arg(short, long)]
        path: PathBuf,
    },
    /// Verifies deterministic bytecode generation from source
    Verify {
        /// The path to the SynQ source file
        #[arg(short = 's', long)]
        source: PathBuf,
        /// The path to the compiled SynQ bytecode file
        #[arg(short = 'b', long)]
        bytecode: PathBuf,
        /// Execute the verified bytecode after match validation
        #[arg(long, default_value_t = false)]
        run: bool,
    },
}

fn main() {
    let cli = Cli::parse();

    let result = match &cli.command {
        Commands::Init { name, force } => init_project(name, *force),
        Commands::Build { path } => build(path),
        Commands::Check { path } => check(path),
        Commands::Abi { path, output } => emit_abi(path, output.as_deref()),
        Commands::Manifest { path, output } => emit_manifest(path, output.as_deref()),
        Commands::Keygen {
            algorithm,
            network,
            out_dir,
            name,
            force,
        } => keygen(algorithm, network, out_dir, name, *force),
        Commands::SignDeploy {
            bytecode,
            manifest,
            abi,
            private_key,
            args,
            output,
            chain,
            network,
            nonce,
            not_before_unix,
            expiration_unix,
            force,
        } => sign_deploy(SignDeployOptions {
            bytecode,
            manifest,
            abi,
            private_key,
            args: args.as_deref(),
            output,
            chain: *chain,
            network,
            nonce: *nonce,
            not_before_unix: *not_before_unix,
            expiration_unix: *expiration_unix,
            force: *force,
        }),
        Commands::VerifyDeploy {
            envelope,
            chain,
            network,
            now_unix,
        } => verify_deploy(envelope, *chain, network, *now_unix),
        Commands::SignCall {
            contract,
            method,
            abi,
            manifest,
            private_key,
            args,
            output,
            chain,
            network,
            nonce,
            not_before_unix,
            expiration_unix,
            force,
        } => sign_call(SignCallOptions {
            contract,
            method,
            abi,
            manifest,
            private_key,
            args: args.as_deref(),
            output,
            chain: *chain,
            network,
            nonce: *nonce,
            not_before_unix: *not_before_unix,
            expiration_unix: *expiration_unix,
            force: *force,
        }),
        Commands::VerifyCall {
            envelope,
            chain,
            network,
            now_unix,
        } => verify_call(envelope, *chain, network, *now_unix),
        Commands::Simulate { path } => simulate(path),
        Commands::Compile { path } => compile(path),
        Commands::Run { path } => run(path),
        Commands::Verify {
            source,
            bytecode,
            run,
        } => verify(source, bytecode, *run),
    };

    if let Err(err) = result {
        eprintln!("Error: {err}");
        process::exit(1);
    }
}

fn init_project(project_dir: &Path, force: bool) -> Result<(), String> {
    let contracts_dir = project_dir.join("contracts");
    let tests_dir = project_dir.join("tests");
    let scripts_dir = project_dir.join("scripts");
    fs::create_dir_all(&contracts_dir).map_err(|e| {
        format!(
            "Failed to create contracts directory {}: {e}",
            contracts_dir.display()
        )
    })?;
    fs::create_dir_all(&tests_dir).map_err(|e| {
        format!(
            "Failed to create tests directory {}: {e}",
            tests_dir.display()
        )
    })?;
    fs::create_dir_all(&scripts_dir).map_err(|e| {
        format!(
            "Failed to create scripts directory {}: {e}",
            scripts_dir.display()
        )
    })?;

    write_template(&project_dir.join("synq.toml"), SYNQ_TOML_TEMPLATE, force)?;
    write_template(&contracts_dir.join("Counter.synq"), COUNTER_TEMPLATE, force)?;
    write_template(&project_dir.join(".gitignore"), GITIGNORE_TEMPLATE, force)?;
    write_template(&tests_dir.join(".gitkeep"), "", force)?;
    write_template(
        &scripts_dir.join("deploy-local-demo.sh"),
        DEPLOY_LOCAL_DEMO_TEMPLATE,
        force,
    )?;

    println!("✓ Created SynQ project: {}", project_dir.display());
    println!(
        "✓ Contract: {}",
        contracts_dir.join("Counter.synq").display()
    );
    println!("✓ Config: {}", project_dir.join("synq.toml").display());
    println!(
        "Next: synq build {}",
        contracts_dir.join("Counter.synq").display()
    );
    Ok(())
}

fn write_template(path: &Path, contents: &str, force: bool) -> Result<(), String> {
    if path.exists() && !force {
        return Err(format!(
            "Refusing to overwrite existing file {}. Re-run with --force to replace scaffold files.",
            path.display()
        ));
    }
    fs::write(path, contents).map_err(|e| format!("Failed to write {}: {e}", path.display()))
}

fn compile(path: &Path) -> Result<(), String> {
    println!("Compiling: {}", path.display());
    let compiled = compile_source(path)?;

    // Generate .synq bytecode
    let (synq_path, sol_path) = derive_output_paths(path);
    fs::write(&synq_path, &compiled.bundle.bytecode)
        .map_err(|e| format!("Failed to write .synq file: {e}"))?;
    println!("✓ Generated: {}", synq_path.display());

    // Generate .sol Solidity code
    fs::write(&sol_path, &compiled.solidity_code)
        .map_err(|e| format!("Failed to write .sol file: {e}"))?;
    println!("✓ Generated: {}", sol_path.display());
    println!("{}", compiler::SOLIDITY_COMPATIBILITY_WARNING);

    println!("Compilation complete!");
    Ok(())
}

fn check(path: &Path) -> Result<(), String> {
    let compiled = compile_source(path)?;
    println!("✓ Check succeeded: {}", path.display());
    println!("contract={}", compiled.bundle.abi.contract);
    println!("bytecode_hash={}", compiled.bundle.hashes.bytecode_hash);
    println!("abi_hash={}", compiled.bundle.hashes.abi_hash);
    println!("manifest_hash={}", compiled.bundle.hashes.manifest_hash);
    Ok(())
}

fn build(path: &Path) -> Result<(), String> {
    println!("Building canonical SynQ artifacts: {}", path.display());
    let compiled = compile_source(path)?;
    let output = derive_build_output_paths(path);

    fs::write(&output.bytecode, &compiled.bundle.bytecode)
        .map_err(|e| format!("Failed to write bytecode artifact: {e}"))?;
    fs::write(&output.abi, compiled.bundle.abi_json()?)
        .map_err(|e| format!("Failed to write ABI artifact: {e}"))?;
    fs::write(&output.manifest, compiled.bundle.manifest_json()?)
        .map_err(|e| format!("Failed to write manifest artifact: {e}"))?;
    fs::write(&output.solidity_compatibility, &compiled.solidity_code)
        .map_err(|e| format!("Failed to write Solidity compatibility artifact: {e}"))?;

    println!("✓ Bytecode: {}", output.bytecode.display());
    println!("✓ ABI: {}", output.abi.display());
    println!("✓ Manifest: {}", output.manifest.display());
    println!(
        "✓ Solidity compatibility output: {}",
        output.solidity_compatibility.display()
    );
    println!("{}", compiler::SOLIDITY_COMPATIBILITY_WARNING);
    println!(
        "bytecode_hash={}\nabi_hash={}\nmanifest_hash={}",
        compiled.bundle.hashes.bytecode_hash,
        compiled.bundle.hashes.abi_hash,
        compiled.bundle.hashes.manifest_hash
    );
    println!("Build complete!");
    Ok(())
}

fn emit_abi(path: &Path, output: Option<&Path>) -> Result<(), String> {
    let compiled = compile_source(path)?;
    write_or_print(output, &compiled.bundle.abi_json()?, "ABI")
}

fn emit_manifest(path: &Path, output: Option<&Path>) -> Result<(), String> {
    let compiled = compile_source(path)?;
    write_or_print(output, &compiled.bundle.manifest_json()?, "manifest")
}

#[derive(Debug, Serialize, Deserialize)]
struct SynqPrivateKeyFile {
    version: u16,
    algorithm: String,
    chain_id: u64,
    network_id: String,
    address: String,
    public_key_hex: String,
    private_key_hex: String,
}

#[derive(Debug, Serialize)]
struct SynqPublicKeyFile {
    version: u16,
    algorithm: String,
    chain_id: u64,
    network_id: String,
    address: String,
    public_key_hex: String,
}

struct SignDeployOptions<'a> {
    bytecode: &'a Path,
    manifest: &'a Path,
    abi: &'a Path,
    private_key: &'a Path,
    args: Option<&'a str>,
    output: &'a Path,
    chain: u64,
    network: &'a str,
    nonce: u64,
    not_before_unix: u64,
    expiration_unix: u64,
    force: bool,
}

struct SignCallOptions<'a> {
    contract: &'a str,
    method: &'a str,
    abi: &'a Path,
    manifest: &'a Path,
    private_key: &'a Path,
    args: Option<&'a str>,
    output: &'a Path,
    chain: u64,
    network: &'a str,
    nonce: u64,
    not_before_unix: u64,
    expiration_unix: u64,
    force: bool,
}

fn keygen(
    algorithm: &str,
    network: &str,
    out_dir: &Path,
    name: &str,
    force: bool,
) -> Result<(), String> {
    validate_account_domain_algorithm(algorithm)?;
    let network_id = normalize_cli_network(compiler::artifacts::SYNQ_TESTNET_CHAIN_ID, network)?;
    fs::create_dir_all(out_dir).map_err(|e| {
        format!(
            "Failed to create key output directory {}: {e}",
            out_dir.display()
        )
    })?;

    let signer = Sign::mldsa87();
    let (public_key_bytes, private_key_bytes) = signer
        .keygen()
        .map_err(|e| format!("aegis-pqsynq ML-DSA-87 keygen failed: {e}"))?;
    let public_key = SynQPublicKey::new(public_key_bytes.clone());
    let address = derive_synq_address(
        &public_key,
        AlgorithmId::MlDsa87,
        &NetworkId(network_id.clone()),
    )
    .map_err(|e| format!("aegis-pqsynq address derivation failed: {e}"))?;

    let private = SynqPrivateKeyFile {
        version: 1,
        algorithm: compiler::artifacts::SYNQ_TESTNET_SIGNATURE_ALGORITHM.to_string(),
        chain_id: compiler::artifacts::SYNQ_TESTNET_CHAIN_ID,
        network_id: network_id.clone(),
        address: address.to_execution_signer_id(),
        public_key_hex: hex::encode(&public_key_bytes),
        private_key_hex: hex::encode(&private_key_bytes),
    };
    let public = SynqPublicKeyFile {
        version: private.version,
        algorithm: private.algorithm.clone(),
        chain_id: private.chain_id,
        network_id,
        address: private.address.clone(),
        public_key_hex: private.public_key_hex.clone(),
    };

    let private_path = out_dir.join(format!("{name}.private.json"));
    let public_path = out_dir.join(format!("{name}.public.json"));
    write_json_file(&private_path, &private, force, true)?;
    write_json_file(&public_path, &public, force, false)?;

    println!("✓ Generated ML-DSA-87 SynQ identity through aegis-pqsynq");
    println!("public_key={}", public_path.display());
    println!("private_key={}", private_path.display());
    println!("address={}", public.address);
    println!("chain_id={}", public.chain_id);
    println!("network_id={}", public.network_id);
    Ok(())
}

fn sign_deploy(options: SignDeployOptions<'_>) -> Result<(), String> {
    if options.output.exists() && !options.force {
        return Err(format!(
            "Refusing to overwrite existing envelope {}. Re-run with --force to replace it.",
            options.output.display()
        ));
    }

    let network_id = normalize_cli_network(options.chain, options.network)?;
    let key = read_private_key(options.private_key)?;
    validate_account_domain_algorithm(&key.algorithm)?;
    if key.chain_id != options.chain {
        return Err(format!(
            "Private key is bound to chain_id `{}`, but signing requested chain_id `{}`",
            key.chain_id, options.chain
        ));
    }
    if key.network_id != network_id {
        return Err(format!(
            "Private key is bound to network_id `{}`, but signing requested network_id `{network_id}`",
            key.network_id
        ));
    }

    let bytecode = fs::read(options.bytecode).map_err(|e| {
        format!(
            "Failed to read bytecode {}: {e}",
            options.bytecode.display()
        )
    })?;
    let manifest = fs::read(options.manifest).map_err(|e| {
        format!(
            "Failed to read manifest {}: {e}",
            options.manifest.display()
        )
    })?;
    let abi = fs::read(options.abi)
        .map_err(|e| format!("Failed to read ABI {}: {e}", options.abi.display()))?;

    let bytecode_hash = sha256_array(&bytecode);
    let manifest_hash = sha256_array(&manifest);
    let abi_hash = sha256_array(&abi);
    validate_manifest_for_signing(
        &manifest,
        &bytecode_hash,
        &abi_hash,
        options.chain,
        &network_id,
    )?;

    let public_key_bytes = hex::decode(&key.public_key_hex).map_err(|e| {
        format!(
            "Invalid public_key_hex in {}: {e}",
            options.private_key.display()
        )
    })?;
    let private_key_bytes = hex::decode(&key.private_key_hex).map_err(|e| {
        format!(
            "Invalid private_key_hex in {}: {e}",
            options.private_key.display()
        )
    })?;
    let public_key = SynQPublicKey::new(public_key_bytes);
    let signer_address = derive_synq_address(
        &public_key,
        AlgorithmId::MlDsa87,
        &NetworkId(network_id.clone()),
    )
    .map_err(|e| format!("aegis-pqsynq address derivation failed: {e}"))?;
    if signer_address.to_execution_signer_id() != key.address {
        return Err(
            "Private key file public key does not derive to its recorded SynQ address".to_string(),
        );
    }

    let constructor_args = canonical_json_args(options.args, "Constructor")?;
    let constructor_args_hash = sha256_array(&constructor_args);
    let payload_hash = hash_contract_deploy_body(
        &bytecode_hash,
        &manifest_hash,
        &abi_hash,
        signer_address.as_bytes(),
        &constructor_args_hash,
    );
    let signing_payload = SynQSigningPayload {
        domain_tag: DomainTag::SynqContractDeployV1,
        chain_id: ChainId(options.chain),
        network_id: NetworkId(network_id.clone()),
        protocol_version: 1,
        algorithm_id: AlgorithmId::MlDsa87,
        signature_purpose: SignaturePurpose::ContractDeploy,
        nonce: options.nonce,
        not_before_unix: options.not_before_unix,
        expiration_unix: options.expiration_unix,
        signer_address,
        payload_hash,
    };
    let canonical = canonicalize_signing_payload(&signing_payload)
        .map_err(|e| format!("aegis-pqsynq canonical payload failed: {e}"))?;
    let signature = Sign::mldsa87()
        .detached_sign(&canonical, &private_key_bytes)
        .map_err(|e| format!("aegis-pqsynq ML-DSA-87 signing failed: {e}"))?;
    let envelope = ContractDeployEnvelope {
        signing_payload,
        public_key,
        signature: SynQSignature::new(signature),
        bytecode_hash,
        manifest_hash,
        abi_hash,
        constructor_args_hash,
    };

    let context = VerificationContext {
        chain_id: ChainId(options.chain),
        network_id: NetworkId(network_id.clone()),
        now_unix: options.not_before_unix,
        policy: pqsynq::SynQSecurityPolicy::testnet_1266_policy(),
    };
    AegisSynQVerifier::testnet_1266()
        .verify_contract_deploy(&envelope, &context)
        .map_err(|e| format!("aegis-pqsynq self-verification failed: {} ({e})", e.code()))?;

    write_json_file(options.output, &envelope, options.force, false)?;
    println!("✓ Signed SynQ deploy envelope through aegis-pqsynq");
    println!("envelope={}", options.output.display());
    println!("domain=SYNQ_CONTRACT_DEPLOY_V1");
    println!("algorithm=ML-DSA-87");
    println!("chain_id={}", options.chain);
    println!("network_id={network_id}");
    println!("signer={}", key.address);
    println!("payload_hash={}", hex::encode(payload_hash));
    println!("bytecode_hash={}", hex::encode(bytecode_hash));
    println!("manifest_hash={}", hex::encode(manifest_hash));
    println!("abi_hash={}", hex::encode(abi_hash));
    println!(
        "constructor_args_hash={}",
        hex::encode(constructor_args_hash)
    );
    Ok(())
}

fn verify_deploy(
    envelope_path: &Path,
    chain: u64,
    network: &str,
    now_unix: u64,
) -> Result<(), String> {
    let network_id = normalize_cli_network(chain, network)?;
    let bytes = fs::read(envelope_path)
        .map_err(|e| format!("Failed to read envelope {}: {e}", envelope_path.display()))?;
    let envelope: ContractDeployEnvelope = serde_json::from_slice(&bytes).map_err(|e| {
        format!(
            "Failed to parse deploy envelope {}: {e}",
            envelope_path.display()
        )
    })?;
    let context = VerificationContext {
        chain_id: ChainId(chain),
        network_id: NetworkId(network_id.clone()),
        now_unix,
        policy: pqsynq::SynQSecurityPolicy::testnet_1266_policy(),
    };
    let verified = AegisSynQVerifier::testnet_1266()
        .verify_contract_deploy(&envelope, &context)
        .map_err(|e| {
            format!(
                "aegis-pqsynq deploy verification failed: {} ({e})",
                e.code()
            )
        })?;

    println!("✓ Deploy envelope verified through aegis-pqsynq");
    println!("deployer={}", verified.deployer.to_execution_signer_id());
    println!("domain=SYNQ_CONTRACT_DEPLOY_V1");
    println!("algorithm=ML-DSA-87");
    println!("chain_id={chain}");
    println!("network_id={network_id}");
    println!(
        "payload_hash={}",
        hex::encode(envelope.signing_payload.payload_hash)
    );
    println!("bytecode_hash={}", hex::encode(verified.bytecode_hash));
    println!("manifest_hash={}", hex::encode(verified.manifest_hash));
    println!("abi_hash={}", hex::encode(verified.abi_hash));
    Ok(())
}

fn sign_call(options: SignCallOptions<'_>) -> Result<(), String> {
    if options.output.exists() && !options.force {
        return Err(format!(
            "Refusing to overwrite existing envelope {}. Re-run with --force to replace it.",
            options.output.display()
        ));
    }

    let network_id = normalize_cli_network(options.chain, options.network)?;
    let key = read_private_key(options.private_key)?;
    validate_account_domain_algorithm(&key.algorithm)?;
    if key.chain_id != options.chain {
        return Err(format!(
            "Private key is bound to chain_id `{}`, but call signing requested chain_id `{}`",
            key.chain_id, options.chain
        ));
    }
    if key.network_id != network_id {
        return Err(format!(
            "Private key is bound to network_id `{}`, but call signing requested network_id `{network_id}`",
            key.network_id
        ));
    }

    let abi = fs::read(options.abi)
        .map_err(|e| format!("Failed to read ABI {}: {e}", options.abi.display()))?;
    let manifest = fs::read(options.manifest).map_err(|e| {
        format!(
            "Failed to read manifest {}: {e}",
            options.manifest.display()
        )
    })?;
    let abi_hash = sha256_array(&abi);
    validate_manifest_policy_for_call(&manifest, &abi_hash, options.chain, &network_id)?;

    let method_selector = method_selector_from_abi(&abi, options.method)?;
    let encoded_args = canonical_json_args(options.args, "Call")?;
    let encoded_args_hash = sha256_array(&encoded_args);
    let contract_address = parse_synq_address(options.contract)?;

    let public_key_bytes = hex::decode(&key.public_key_hex).map_err(|e| {
        format!(
            "Invalid public_key_hex in {}: {e}",
            options.private_key.display()
        )
    })?;
    let private_key_bytes = hex::decode(&key.private_key_hex).map_err(|e| {
        format!(
            "Invalid private_key_hex in {}: {e}",
            options.private_key.display()
        )
    })?;
    let public_key = SynQPublicKey::new(public_key_bytes);
    let signer_address = derive_synq_address(
        &public_key,
        AlgorithmId::MlDsa87,
        &NetworkId(network_id.clone()),
    )
    .map_err(|e| format!("aegis-pqsynq address derivation failed: {e}"))?;
    if signer_address.to_execution_signer_id() != key.address {
        return Err(
            "Private key file public key does not derive to its recorded SynQ address".to_string(),
        );
    }

    let payload_hash = hash_contract_call_body(
        contract_address.as_bytes(),
        &method_selector,
        &encoded_args_hash,
        signer_address.as_bytes(),
    );
    let signing_payload = SynQSigningPayload {
        domain_tag: DomainTag::SynqContractCallV1,
        chain_id: ChainId(options.chain),
        network_id: NetworkId(network_id.clone()),
        protocol_version: 1,
        algorithm_id: AlgorithmId::MlDsa87,
        signature_purpose: SignaturePurpose::ContractCall,
        nonce: options.nonce,
        not_before_unix: options.not_before_unix,
        expiration_unix: options.expiration_unix,
        signer_address,
        payload_hash,
    };
    let canonical = canonicalize_signing_payload(&signing_payload)
        .map_err(|e| format!("aegis-pqsynq canonical call payload failed: {e}"))?;
    let signature = Sign::mldsa87()
        .detached_sign(&canonical, &private_key_bytes)
        .map_err(|e| format!("aegis-pqsynq ML-DSA-87 call signing failed: {e}"))?;
    let envelope = ContractCallEnvelope {
        signing_payload,
        public_key,
        signature: SynQSignature::new(signature),
        contract_address,
        method_selector,
        encoded_args_hash,
    };

    let context = VerificationContext {
        chain_id: ChainId(options.chain),
        network_id: NetworkId(network_id.clone()),
        now_unix: options.not_before_unix,
        policy: pqsynq::SynQSecurityPolicy::testnet_1266_policy(),
    };
    AegisSynQVerifier::testnet_1266()
        .verify_contract_call(&envelope, &context)
        .map_err(|e| {
            format!(
                "aegis-pqsynq call self-verification failed: {} ({e})",
                e.code()
            )
        })?;

    write_json_file(options.output, &envelope, options.force, false)?;
    println!("✓ Signed SynQ call envelope through aegis-pqsynq");
    println!("envelope={}", options.output.display());
    println!("domain=SYNQ_CONTRACT_CALL_V1");
    println!("algorithm=ML-DSA-87");
    println!("chain_id={}", options.chain);
    println!("network_id={network_id}");
    println!("method={}", options.method);
    println!("method_selector=0x{}", hex::encode(method_selector));
    println!("args_hash={}", hex::encode(encoded_args_hash));
    println!(
        "contract={}",
        envelope.contract_address.to_execution_signer_id()
    );
    println!("signer={}", key.address);
    println!("payload_hash={}", hex::encode(payload_hash));
    Ok(())
}

fn verify_call(
    envelope_path: &Path,
    chain: u64,
    network: &str,
    now_unix: u64,
) -> Result<(), String> {
    let network_id = normalize_cli_network(chain, network)?;
    let bytes = fs::read(envelope_path).map_err(|e| {
        format!(
            "Failed to read call envelope {}: {e}",
            envelope_path.display()
        )
    })?;
    let envelope: ContractCallEnvelope = serde_json::from_slice(&bytes).map_err(|e| {
        format!(
            "Failed to parse call envelope {}: {e}",
            envelope_path.display()
        )
    })?;
    let context = VerificationContext {
        chain_id: ChainId(chain),
        network_id: NetworkId(network_id.clone()),
        now_unix,
        policy: pqsynq::SynQSecurityPolicy::testnet_1266_policy(),
    };
    let verified = AegisSynQVerifier::testnet_1266()
        .verify_contract_call(&envelope, &context)
        .map_err(|e| format!("aegis-pqsynq call verification failed: {} ({e})", e.code()))?;

    println!("✓ Call envelope verified through aegis-pqsynq");
    println!("caller={}", verified.caller.to_execution_signer_id());
    println!(
        "contract={}",
        verified.contract_address.to_execution_signer_id()
    );
    println!("domain=SYNQ_CONTRACT_CALL_V1");
    println!("algorithm=ML-DSA-87");
    println!("chain_id={chain}");
    println!("network_id={network_id}");
    println!(
        "method_selector=0x{}",
        hex::encode(verified.method_selector)
    );
    println!(
        "payload_hash={}",
        hex::encode(envelope.signing_payload.payload_hash)
    );
    println!("args_hash={}", hex::encode(envelope.encoded_args_hash));
    Ok(())
}

fn write_or_print(output: Option<&Path>, bytes: &[u8], label: &str) -> Result<(), String> {
    match output {
        Some(path) => {
            fs::write(path, bytes).map_err(|e| format!("Failed to write {label} file: {e}"))?;
            println!("✓ Generated {label}: {}", path.display());
        }
        None => {
            println!(
                "{}",
                std::str::from_utf8(bytes)
                    .map_err(|e| format!("Generated {label} was not valid UTF-8: {e}"))?
            );
        }
    }
    Ok(())
}

fn simulate(path: &Path) -> Result<(), String> {
    println!("Simulating: {}", path.display());
    let compiled = compile_source(path)?;
    execute_bytecode(&compiled.bundle.bytecode)?;
    println!("✓ Simulation succeeded");
    println!("bytecode_hash={}", compiled.bundle.hashes.bytecode_hash);
    Ok(())
}

fn run(path: &Path) -> Result<(), String> {
    println!("Running: {}", path.display());
    let bytecode = fs::read(path).map_err(|e| format!("Failed to read bytecode file: {e}"))?;
    execute_bytecode(&bytecode)?;
    println!("Execution finished successfully");
    Ok(())
}

const COUNTER_TEMPLATE: &str = r#"contract Counter {
    counter: UInt256 public;

    @public function increment() -> UInt256 {
        counter = counter + 1;
        return counter;
    }

    @public function get() -> UInt256 {
        return counter;
    }
}
"#;

const SYNQ_TOML_TEMPLATE: &str = r#"[package]
name = "counter"
version = "0.1.0"

[compiler]
language_version = "0.1"
bytecode_version = 2
target_aivm_version = "0.1"

[network]
chain_id = 1266
network_id = "synergy-testnet"
address_hrp = "tsynq"

[security]
signature_algorithm = "ML-DSA-87"
deploy_domain = "SYNQ_CONTRACT_DEPLOY_V1"
call_domain = "SYNQ_CONTRACT_CALL_V1"
"#;

const GITIGNORE_TEMPLATE: &str = r#"/keys/
*.compiled.synq
*.abi.json
*.manifest.json
*.sol
"#;

const DEPLOY_LOCAL_DEMO_TEMPLATE: &str = r#"#!/usr/bin/env bash
set -euo pipefail
echo "Local demo only. This does not submit to public TESTNET."
synq build contracts/Counter.synq
"#;

fn verify(source_path: &Path, bytecode_path: &Path, run_after_verify: bool) -> Result<(), String> {
    println!(
        "Verifying bytecode determinism:\n  source: {}\n  bytecode: {}",
        source_path.display(),
        bytecode_path.display()
    );

    let generated = compile_source(source_path)?.bundle.bytecode;
    let provided = fs::read(bytecode_path).map_err(|e| {
        format!(
            "Failed to read bytecode file {}: {e}",
            bytecode_path.display()
        )
    })?;

    if generated != provided {
        let generated_hash = sha256_hex(&generated);
        let provided_hash = sha256_hex(&provided);
        let diff_index = first_diff_index(&generated, &provided)
            .map(|idx| idx.to_string())
            .unwrap_or_else(|| "length mismatch".to_string());

        return Err(format!(
            "Bytecode mismatch (first difference: {diff_index}). generated_sha256={generated_hash} provided_sha256={provided_hash}"
        ));
    }

    println!(
        "✓ Verification succeeded: source and bytecode match (sha256={})",
        sha256_hex(&provided)
    );

    if run_after_verify {
        execute_bytecode(&provided)?;
        println!("Execution finished successfully");
    }

    Ok(())
}

struct CompiledSource {
    bundle: compiler::ArtifactBundle,
    solidity_code: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SynqProjectConfig {
    package: Option<SynqPackageConfig>,
    compiler: Option<SynqCompilerConfig>,
    network: Option<SynqNetworkConfig>,
    security: Option<SynqSecurityConfig>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SynqPackageConfig {
    name: String,
    version: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SynqCompilerConfig {
    language_version: String,
    bytecode_version: u16,
    target_aivm_version: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SynqNetworkConfig {
    chain_id: u64,
    network_id: String,
    address_hrp: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SynqSecurityConfig {
    signature_algorithm: String,
    deploy_domain: String,
    call_domain: String,
}

fn compile_source(path: &Path) -> Result<CompiledSource, String> {
    let source = fs::read_to_string(path)
        .map_err(|e| format!("Failed to read source file {}: {e}", path.display()))?;
    let artifact_config = load_artifact_config(path)?;
    let (_version_req, ast) = compiler::parse(&source)
        .map_err(|e| format!("Failed to parse source file {}: {e}", path.display()))?;
    compiler::analyze(&ast).map_err(|errors| format_semantic_errors(path, &errors))?;

    let codegen = compiler::CodeGenerator::new();
    let bytecode = codegen
        .generate_stateful(&ast)
        .map_err(|e| format!("Failed to generate bytecode: {e}"))?;

    let sol_gen = compiler::SolidityGenerator::new();
    let solidity_code = sol_gen
        .generate(&ast)
        .map_err(|e| format!("Failed to generate Solidity code: {e}"))?;

    let bundle =
        compiler::ArtifactBundle::generate_with_config(&source, &ast, bytecode, &artifact_config)
            .map_err(|e| format!("Failed to generate canonical artifacts: {e}"))?;

    Ok(CompiledSource {
        bundle,
        solidity_code,
    })
}

fn load_artifact_config(source_path: &Path) -> Result<compiler::ArtifactConfig, String> {
    let Some(config_path) = find_synq_toml(source_path) else {
        return Ok(compiler::ArtifactConfig::testnet_1266());
    };

    let contents = fs::read_to_string(&config_path)
        .map_err(|e| format!("Failed to read config {}: {e}", config_path.display()))?;
    let config: SynqProjectConfig = toml::from_str(&contents)
        .map_err(|e| format!("Failed to parse config {}: {e}", config_path.display()))?;

    config.to_artifact_config(&config_path)
}

fn find_synq_toml(source_path: &Path) -> Option<PathBuf> {
    let mut current = if source_path.is_dir() {
        source_path.to_path_buf()
    } else {
        source_path.parent()?.to_path_buf()
    };

    loop {
        let candidate = current.join("synq.toml");
        if candidate.exists() {
            return Some(candidate);
        }
        if !current.pop() {
            return None;
        }
    }
}

impl SynqProjectConfig {
    fn to_artifact_config(&self, config_path: &Path) -> Result<compiler::ArtifactConfig, String> {
        let package = self
            .package
            .as_ref()
            .ok_or_else(|| format!("Config {} is missing [package]", config_path.display()))?;
        package.validate(config_path)?;

        let compiler_config = self
            .compiler
            .as_ref()
            .ok_or_else(|| format!("Config {} is missing [compiler]", config_path.display()))?;
        compiler_config.validate(config_path)?;

        let network = self
            .network
            .as_ref()
            .ok_or_else(|| format!("Config {} is missing [network]", config_path.display()))?;
        network.validate(config_path)?;

        let security = self
            .security
            .as_ref()
            .ok_or_else(|| format!("Config {} is missing [security]", config_path.display()))?;
        security.validate(config_path)?;

        Ok(compiler::ArtifactConfig {
            bytecode_version: compiler_config.bytecode_version,
            required_aivm_version: compiler_config.target_aivm_version.clone(),
            required_chain_id: network.chain_id,
            required_network_id: network.network_id.clone(),
            required_signature_algorithm: security.signature_algorithm.clone(),
            security_policy: compiler::artifacts::SYNQ_TESTNET_SECURITY_POLICY.to_string(),
        })
    }
}

impl SynqPackageConfig {
    fn validate(&self, config_path: &Path) -> Result<(), String> {
        if self.name.trim().is_empty() {
            return Err(format!(
                "Config {} has an empty package.name",
                config_path.display()
            ));
        }
        if self.version.trim().is_empty() {
            return Err(format!(
                "Config {} has an empty package.version",
                config_path.display()
            ));
        }
        Ok(())
    }
}

impl SynqCompilerConfig {
    fn validate(&self, config_path: &Path) -> Result<(), String> {
        if self.language_version != compiler::artifacts::SYNQ_MANIFEST_VERSION {
            return Err(format!(
                "Config {} uses unsupported compiler.language_version `{}`; supported SynQ language version is `{}`",
                config_path.display(),
                self.language_version,
                compiler::artifacts::SYNQ_MANIFEST_VERSION
            ));
        }
        if self.bytecode_version != compiler::artifacts::SYNQ_BYTECODE_VERSION {
            return Err(format!(
                "Config {} uses unsupported compiler.bytecode_version `{}`; supported bytecode version is `{}`",
                config_path.display(),
                self.bytecode_version,
                compiler::artifacts::SYNQ_BYTECODE_VERSION
            ));
        }
        if self.target_aivm_version.trim().is_empty() {
            return Err(format!(
                "Config {} has an empty compiler.target_aivm_version",
                config_path.display()
            ));
        }
        Ok(())
    }
}

impl SynqNetworkConfig {
    fn validate(&self, config_path: &Path) -> Result<(), String> {
        if self.chain_id != compiler::artifacts::SYNQ_TESTNET_CHAIN_ID {
            return Err(format!(
                "Config {} uses unsupported network.chain_id `{}`; SynQ deploy artifacts are currently bound to chain_id `{}`",
                config_path.display(),
                self.chain_id,
                compiler::artifacts::SYNQ_TESTNET_CHAIN_ID
            ));
        }
        if !matches!(
            self.network_id.as_str(),
            compiler::artifacts::SYNQ_TESTNET_NETWORK_ID | "synergy-testnet-v3"
        ) {
            return Err(format!(
                "Config {} uses unsupported network.network_id `{}`; expected `synergy-testnet` or the chain-1266 node alias `synergy-testnet-v3`",
                config_path.display(),
                self.network_id
            ));
        }
        if self.address_hrp != "tsynq" {
            return Err(format!(
                "Config {} uses unsupported network.address_hrp `{}`; expected `tsynq`",
                config_path.display(),
                self.address_hrp
            ));
        }
        Ok(())
    }
}

impl SynqSecurityConfig {
    fn validate(&self, config_path: &Path) -> Result<(), String> {
        if self.signature_algorithm != compiler::artifacts::SYNQ_TESTNET_SIGNATURE_ALGORITHM {
            return Err(format!(
                "Config {} uses unsupported security.signature_algorithm `{}`; launch policy requires `{}`",
                config_path.display(),
                self.signature_algorithm,
                compiler::artifacts::SYNQ_TESTNET_SIGNATURE_ALGORITHM
            ));
        }
        if self.deploy_domain != "SYNQ_CONTRACT_DEPLOY_V1" {
            return Err(format!(
                "Config {} uses unsupported security.deploy_domain `{}`; expected `SYNQ_CONTRACT_DEPLOY_V1`",
                config_path.display(),
                self.deploy_domain
            ));
        }
        if self.call_domain != "SYNQ_CONTRACT_CALL_V1" {
            return Err(format!(
                "Config {} uses unsupported security.call_domain `{}`; expected `SYNQ_CONTRACT_CALL_V1`",
                config_path.display(),
                self.call_domain
            ));
        }
        Ok(())
    }
}

fn validate_account_domain_algorithm(algorithm: &str) -> Result<(), String> {
    let normalized = algorithm
        .chars()
        .filter(|ch| *ch != '-' && *ch != '_')
        .flat_map(|ch| ch.to_lowercase())
        .collect::<String>();
    if normalized == "mldsa87" {
        Ok(())
    } else {
        Err(format!(
            "Unsupported signature algorithm `{algorithm}`; launch policy requires the account-domain algorithm ML-DSA-87"
        ))
    }
}

fn normalize_cli_network(chain_id: u64, network: &str) -> Result<String, String> {
    if chain_id != compiler::artifacts::SYNQ_TESTNET_CHAIN_ID {
        return Err(format!(
            "Unsupported chain_id `{chain_id}`; SynQ deploy payloads are currently bound to chain_id `{}`",
            compiler::artifacts::SYNQ_TESTNET_CHAIN_ID
        ));
    }

    match network {
        "testnet" | compiler::artifacts::SYNQ_TESTNET_NETWORK_ID | "synergy-testnet-v3" => {
            Ok(compiler::artifacts::SYNQ_TESTNET_NETWORK_ID.to_string())
        }
        other => Err(format!(
            "Unsupported network `{other}`; expected `testnet`, `synergy-testnet`, or chain-1266 alias `synergy-testnet-v3`"
        )),
    }
}

fn write_json_file<T: Serialize>(
    path: &Path,
    value: &T,
    force: bool,
    private: bool,
) -> Result<(), String> {
    if path.exists() && !force {
        return Err(format!(
            "Refusing to overwrite existing file {}. Re-run with --force to replace it.",
            path.display()
        ));
    }
    let bytes = serde_json::to_vec_pretty(value)
        .map_err(|e| format!("Failed to encode JSON for {}: {e}", path.display()))?;
    fs::write(path, bytes).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
    if private {
        set_private_file_permissions(path)?;
    }
    Ok(())
}

#[cfg(unix)]
fn set_private_file_permissions(path: &Path) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;

    let mut permissions = fs::metadata(path)
        .map_err(|e| format!("Failed to inspect {} permissions: {e}", path.display()))?
        .permissions();
    permissions.set_mode(0o600);
    fs::set_permissions(path, permissions)
        .map_err(|e| format!("Failed to restrict {} permissions: {e}", path.display()))
}

#[cfg(not(unix))]
fn set_private_file_permissions(_path: &Path) -> Result<(), String> {
    Ok(())
}

fn read_private_key(path: &Path) -> Result<SynqPrivateKeyFile, String> {
    let bytes =
        fs::read(path).map_err(|e| format!("Failed to read key {}: {e}", path.display()))?;
    let key: SynqPrivateKeyFile = serde_json::from_slice(&bytes)
        .map_err(|e| format!("Failed to parse key {}: {e}", path.display()))?;
    if key.version != 1 {
        return Err(format!(
            "Unsupported key file version `{}` in {}",
            key.version,
            path.display()
        ));
    }
    Ok(key)
}

fn validate_manifest_for_signing(
    manifest_bytes: &[u8],
    bytecode_hash: &[u8; 32],
    abi_hash: &[u8; 32],
    chain_id: u64,
    network_id: &str,
) -> Result<(), String> {
    let manifest: serde_json::Value = serde_json::from_slice(manifest_bytes)
        .map_err(|e| format!("Failed to parse manifest JSON: {e}"))?;
    expect_manifest_hex(&manifest, "bytecode_hash", bytecode_hash)?;
    expect_manifest_hex(&manifest, "abi_hash", abi_hash)?;

    let manifest_chain = manifest
        .get("required_chain_id")
        .and_then(serde_json::Value::as_u64)
        .ok_or_else(|| "Manifest missing numeric required_chain_id".to_string())?;
    if manifest_chain != chain_id {
        return Err(format!(
            "Manifest required_chain_id `{manifest_chain}` does not match signing chain_id `{chain_id}`"
        ));
    }

    let manifest_network = manifest
        .get("required_network_id")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| "Manifest missing string required_network_id".to_string())?;
    let normalized_manifest_network = normalize_cli_network(manifest_chain, manifest_network)?;
    if normalized_manifest_network != network_id {
        return Err(format!(
            "Manifest required_network_id `{manifest_network}` does not match signing network `{network_id}`"
        ));
    }

    let signature_algorithm = manifest
        .get("required_signature_algorithm")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| "Manifest missing string required_signature_algorithm".to_string())?;
    validate_account_domain_algorithm(signature_algorithm)?;

    Ok(())
}

fn validate_manifest_policy_for_call(
    manifest_bytes: &[u8],
    abi_hash: &[u8; 32],
    chain_id: u64,
    network_id: &str,
) -> Result<(), String> {
    let manifest: serde_json::Value = serde_json::from_slice(manifest_bytes)
        .map_err(|e| format!("Failed to parse manifest JSON: {e}"))?;
    expect_manifest_hex(&manifest, "abi_hash", abi_hash)?;

    let manifest_chain = manifest
        .get("required_chain_id")
        .and_then(serde_json::Value::as_u64)
        .ok_or_else(|| "Manifest missing numeric required_chain_id".to_string())?;
    if manifest_chain != chain_id {
        return Err(format!(
            "Manifest required_chain_id `{manifest_chain}` does not match call signing chain_id `{chain_id}`"
        ));
    }

    let manifest_network = manifest
        .get("required_network_id")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| "Manifest missing string required_network_id".to_string())?;
    let normalized_manifest_network = normalize_cli_network(manifest_chain, manifest_network)?;
    if normalized_manifest_network != network_id {
        return Err(format!(
            "Manifest required_network_id `{manifest_network}` does not match call signing network `{network_id}`"
        ));
    }

    let signature_algorithm = manifest
        .get("required_signature_algorithm")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| "Manifest missing string required_signature_algorithm".to_string())?;
    validate_account_domain_algorithm(signature_algorithm)?;
    Ok(())
}

fn method_selector_from_abi(abi_bytes: &[u8], method: &str) -> Result<[u8; 4], String> {
    let abi: serde_json::Value =
        serde_json::from_slice(abi_bytes).map_err(|e| format!("Failed to parse ABI JSON: {e}"))?;
    let methods = abi
        .get("methods")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "ABI missing methods array".to_string())?;
    let method_json = methods
        .iter()
        .find(|entry| entry.get("name").and_then(serde_json::Value::as_str) == Some(method))
        .ok_or_else(|| format!("ABI does not contain method `{method}`"))?;

    let params = method_json
        .get("params")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| format!("ABI method `{method}` is missing params array"))?;
    if !params.is_empty() {
        return Err(format!(
            "CLI call signing currently supports no-argument methods only; `{method}` has {} parameter(s)",
            params.len()
        ));
    }

    let selector = method_json
        .get("selector")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| format!("ABI method `{method}` is missing selector"))?;
    let selector_hex = selector.strip_prefix("0x").unwrap_or(selector);
    let selector_bytes = hex::decode(selector_hex)
        .map_err(|e| format!("ABI method `{method}` has invalid selector `{selector}`: {e}"))?;
    if selector_bytes.len() != 4 {
        return Err(format!(
            "ABI method `{method}` selector `{selector}` is not 4 bytes"
        ));
    }
    let mut out = [0_u8; 4];
    out.copy_from_slice(&selector_bytes);
    Ok(out)
}

fn canonical_json_args(args: Option<&str>, label: &str) -> Result<Vec<u8>, String> {
    let normalized = args.unwrap_or("").trim();
    if normalized.is_empty() || normalized == "[]" {
        return Ok(Vec::new());
    }

    let value: serde_json::Value = serde_json::from_str(normalized)
        .map_err(|e| format!("{label} args must be valid JSON when supplied: {e}"))?;
    let array = value
        .as_array()
        .ok_or_else(|| format!("{label} args must be a JSON array"))?;
    if array.is_empty() {
        return Ok(Vec::new());
    }
    serde_json::to_vec(&value).map_err(|e| format!("Canonicalize {label} args: {e}"))
}

fn parse_synq_address(value: &str) -> Result<SynQAddress, String> {
    let raw = value.trim();
    let hex_value = raw.strip_prefix("tsynq1").unwrap_or(raw);
    let bytes = hex::decode(hex_value)
        .map_err(|e| format!("Invalid SynQ address `{value}` hex encoding: {e}"))?;
    if bytes.len() != pqsynq::address::SYNQ_ADDRESS_LEN {
        return Err(format!(
            "Invalid SynQ address `{value}` length {}; expected {} bytes",
            bytes.len(),
            pqsynq::address::SYNQ_ADDRESS_LEN
        ));
    }
    let mut out = [0_u8; pqsynq::address::SYNQ_ADDRESS_LEN];
    out.copy_from_slice(&bytes);
    Ok(SynQAddress::from_bytes(out))
}

fn expect_manifest_hex(
    manifest: &serde_json::Value,
    field: &str,
    expected: &[u8; 32],
) -> Result<(), String> {
    let actual = manifest
        .get(field)
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| format!("Manifest missing string {field}"))?;
    let expected_hex = hex::encode(expected);
    if actual == expected_hex {
        Ok(())
    } else {
        Err(format!(
            "Manifest {field} `{actual}` does not match artifact hash `{expected_hex}`"
        ))
    }
}

fn derive_output_paths(path: &Path) -> (PathBuf, PathBuf) {
    let synq_path = match path.extension().and_then(|ext| ext.to_str()) {
        Some(ext) if ext.eq_ignore_ascii_case("synq") => path.with_extension("compiled.synq"),
        _ => path.with_extension("synq"),
    };
    let sol_path = path.with_extension("sol");
    (synq_path, sol_path)
}

struct BuildOutputPaths {
    abi: PathBuf,
    bytecode: PathBuf,
    manifest: PathBuf,
    solidity_compatibility: PathBuf,
}

fn derive_build_output_paths(path: &Path) -> BuildOutputPaths {
    let (bytecode, solidity_compatibility) = derive_output_paths(path);
    BuildOutputPaths {
        abi: path.with_extension("abi.json"),
        bytecode,
        manifest: path.with_extension("manifest.json"),
        solidity_compatibility,
    }
}

fn execute_bytecode(bytecode: &[u8]) -> Result<(), String> {
    let executable = compiler::StatefulSynQExecutable::decode(bytecode).ok();
    let executable_bytes = executable
        .as_ref()
        .map(|executable| executable.legacy_quantum_vm_bytecode.as_slice())
        .unwrap_or(bytecode);
    if executable.is_some() && executable_bytes.is_empty() {
        return Err(
            "Stateful SynQ IR requires AIVM execution; no legacy QuantumVM program is available"
                .to_string(),
        );
    }
    let mut vm = quantumvm::QuantumVM::new();
    vm.load_bytecode(executable_bytes)
        .map_err(|e| format!("Failed to load bytecode: {e}"))?;
    vm.execute()
        .map_err(|e| format!("VM execution failed: {e}"))?;
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(sha256_array(bytes))
}

fn sha256_array(bytes: &[u8]) -> [u8; 32] {
    let digest = Sha256::digest(bytes);
    let mut out = [0_u8; 32];
    out.copy_from_slice(&digest);
    out
}

fn first_diff_index(a: &[u8], b: &[u8]) -> Option<usize> {
    let limit = a.len().min(b.len());
    for i in 0..limit {
        if a[i] != b[i] {
            return Some(i);
        }
    }
    if a.len() != b.len() {
        return Some(limit);
    }
    None
}

fn format_semantic_errors(path: &Path, errors: &[compiler::ast::SemanticError]) -> String {
    let mut out = format!("Semantic analysis failed for {}:", path.display());
    for (idx, error) in errors.iter().enumerate() {
        let location = match (error.line, error.column) {
            (Some(line), Some(column)) => format!(" [line {line}, col {column}]"),
            (Some(line), None) => format!(" [line {line}]"),
            _ => String::new(),
        };
        out.push_str(&format!("\n  {}. {}{}", idx + 1, error.message, location));
    }
    out
}
